#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Deployed secrets land here, not in backend/.env, so local development never
# accidentally points at the production database.
ENV_FILE="backend/.env.production"

cd "$(dirname "${BASH_SOURCE[0]}")"

banner "Claude HQ Arena — deploy to Fly.io"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools this wizard drives."
MISSING=0
for tool in fly uv python3 curl; do
  if command -v "$tool" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$tool"
  else
    printf '  %s✗%s %s — not installed\n' "$RED" "$RESET" "$tool"
    MISSING=1
  fi
done
if [[ "$MISSING" -eq 1 ]]; then
  printf '\n'
  warn "Install what's missing, then re-run."
  note "  fly → https://fly.io/docs/flyctl/install/"
  note "  uv  → https://docs.astral.sh/uv/getting-started/installation/"
  exit 1
fi
note "Docker is not needed — images build on Fly's builders (--remote-only)."
printf '\n'
if fly auth whoami >/dev/null 2>&1; then
  printf '  %s✓%s signed in to Fly as %s\n' "$GREEN" "$RESET" "$(fly auth whoami 2>/dev/null)"
else
  warn "Not signed in to Fly."
  step "A browser window will open — sign in there, then come back."
  pause "Press Enter to run 'fly auth login'"
  fly auth login
fi
pause "Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Name the app"
say "This sets the public URL your friends' dashboards will publish to."
note "Lowercase letters, digits and hyphens. It must be globally unique on Fly."
ask FLY_APP "App name [claude-hq-arena]:"
[[ -z "$FLY_APP" ]] && FLY_APP="claude-hq-arena"
if [[ ! "$FLY_APP" =~ ^[a-z0-9][a-z0-9-]*$ ]]; then
  warn "Invalid app name: $FLY_APP"
  exit 1
fi
APP_URL="https://${FLY_APP}.fly.dev"
write_env FLY_APP "$FLY_APP"
write_env APP_URL "$APP_URL"

python3 - "$FLY_APP" "$APP_URL" <<'PY'
import re, sys, pathlib
app, url = sys.argv[1], sys.argv[2]
p = pathlib.Path("backend/fly.toml")
t = p.read_text()
t = re.sub(r'^app = ".*"$', f'app = "{app}"', t, count=1, flags=re.M)
t = re.sub(r'^  ARENA_PUBLIC_BASE_URL = ".*"$',
           f'  ARENA_PUBLIC_BASE_URL = "{url}"', t, count=1, flags=re.M)
p.write_text(t)
print(f"  updated backend/fly.toml → app={app}")
PY

printf '\n'
if fly apps list 2>/dev/null | grep -qE "^${FLY_APP}[[:space:]]"; then
  printf '  %s✓%s app %s already exists\n' "$GREEN" "$RESET" "$FLY_APP"
else
  say "Creating the Fly app (no machines yet, so secrets can be staged)."
  fly apps create "$FLY_APP" || { warn "Could not create $FLY_APP — the name may be taken."; exit 1; }
fi
say "Your Arena URL will be: $APP_URL"
pause "Press Enter to continue"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Neon — Postgres database"
say "Neon's free tier is plenty for a group of friends."
open_url "https://console.neon.tech/app/projects"
step "Click 'New Project'. Any name; pick the region nearest you."
step "When it's created, find the 'Connection string' box on the dashboard."
step "Choose the 'psql' / URI form and copy the whole string."
note "It looks like: postgresql://user:pass@ep-xxx.aws.neon.tech/neondb?sslmode=require"
printf '\n'
ask_secret NEON_URL "Paste the Neon connection string:"
if [[ -z "$NEON_URL" ]]; then
  warn "No connection string given — cannot continue."
  exit 1
fi

# The scheme MUST become postgresql+asyncpg:// -- that is what selects the async
# driver. The query string is then normalised to the single flag the asyncpg
# dialect names natively; SQLAlchemy 2.0.54 also understands Neon's libpq-style
# sslmode/channel_binding, so this is belt-and-braces rather than a fix.
ARENA_DATABASE_URL=$(python3 - "$NEON_URL" <<'PY'
import sys, urllib.parse as u
raw = sys.argv[1].strip()
p = u.urlsplit(raw)
scheme = "postgresql+asyncpg"
netloc, path = p.netloc, p.path
print(u.urlunsplit((scheme, netloc, path, "ssl=require", "")))
PY
)
printf '  %s✓%s converted for asyncpg: %s\n' "$GREEN" "$RESET" \
  "$(printf '%s' "$ARENA_DATABASE_URL" | sed -E 's#//[^:]+:[^@]+@#//***:***@#')"
write_env NEON_URL "$NEON_URL"
write_env ARENA_DATABASE_URL "$ARENA_DATABASE_URL"
pause "Press Enter to continue"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "GitHub — OAuth app"
say "This is how you and your friends sign in to the Arena."
open_url "https://github.com/settings/applications/new"
step "Application name:  Claude HQ Arena"
step "Homepage URL:      $APP_URL"
step "Authorization callback URL — this must match EXACTLY:"
printf '\n      %s%s/v1/auth/github/callback%s\n\n' "$BOLD" "$APP_URL" "$RESET"
step "Click 'Register application'."
step "Copy the Client ID, then click 'Generate a new client secret' and copy that too."
warn "The client secret is shown once. Copy it before leaving the page."
printf '\n'
ask ARENA_GITHUB_CLIENT_ID "Paste the Client ID:"
ask_secret ARENA_GITHUB_CLIENT_SECRET "Paste the Client secret:"
write_env ARENA_GITHUB_CLIENT_ID "$ARENA_GITHUB_CLIENT_ID"
write_env ARENA_GITHUB_CLIENT_SECRET "$ARENA_GITHUB_CLIENT_SECRET"
pause "Press Enter to continue"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Push secrets to Fly"
ARENA_SECRET_KEY=$(_existing ARENA_SECRET_KEY || true)
if [[ -n "$ARENA_SECRET_KEY" ]]; then
  say "Reusing the existing signing key."
  note "Regenerating it would invalidate outstanding pairing codes."
else
  say "Generating a signing key for pairing codes and websocket tickets."
  ARENA_SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")
fi
write_env ARENA_SECRET_KEY "$ARENA_SECRET_KEY"
printf '\n'
say "Staging four secrets on $FLY_APP (applied on the next deploy)."
( cd backend && fly secrets set --stage --app "$FLY_APP" \
    ARENA_DATABASE_URL="$ARENA_DATABASE_URL" \
    ARENA_SECRET_KEY="$ARENA_SECRET_KEY" \
    ARENA_GITHUB_CLIENT_ID="$ARENA_GITHUB_CLIENT_ID" \
    ARENA_GITHUB_CLIENT_SECRET="$ARENA_GITHUB_CLIENT_SECRET" )
printf '  %s✓%s secrets staged\n' "$GREEN" "$RESET"
pause "Press Enter to continue"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Deploy"
say "Building on Fly's remote builders and running database migrations on boot."
warn "This app must stay at ONE machine."
note "Websocket rooms keep presence and shared game state in process memory."
note "A second machine would split players into two invisible copies of each room."
note "Scaling out means putting rooms behind Redis first — see backend/app/rooms.py."
printf '\n'
if ! confirm "Deploy $FLY_APP now?"; then
  SKIPPED+=("deploy (run: cd backend && fly deploy --remote-only)")
  say "Skipped. Run it later with:  cd backend && fly deploy --remote-only"
  pause "Press Enter to continue"
else
  ( cd backend && fly deploy --remote-only --app "$FLY_APP" )
  printf '\n'
  say "Pinning to a single machine."
  fly scale count 1 --app "$FLY_APP" --yes || warn "Could not set machine count — check 'fly status'."
  pause "Press Enter to continue"
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Verify"
say "Checking the deployed health endpoint."
HEALTH=""
for attempt in 1 2 3 4 5; do
  HEALTH=$(curl -fsS --max-time 10 "$APP_URL/health" 2>/dev/null || true)
  [[ -n "$HEALTH" ]] && break
  note "not up yet (attempt $attempt/5) — waiting 6s"
  sleep 6
done
if [[ -n "$HEALTH" ]]; then
  printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$HEALTH"
else
  warn "No response from $APP_URL/health"
  note "Check logs with:  fly logs --app $FLY_APP"
  SKIPPED+=("verify /health — the app did not respond")
fi
printf '\n'
say "Connect your dashboard:"
step "Open Claude HQ → the 🏆 Arena tab."
step "Enter the server URL:  $APP_URL"
step "Click 'Sign in with GitHub', then paste the pairing code back."
printf '\n'
say "Your friends do the same — they each run their own Claude HQ locally,"
say "point it at $APP_URL, and sign in with their own GitHub account."
pause "Press Enter to finish"

finish
printf '  %sArena:%s %s\n' "$BOLD" "$RESET" "$APP_URL"
printf '  %sLogs: %s fly logs --app %s\n' "$DIM" "$RESET" "$FLY_APP"
printf '\n'
