#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

ENV_FILE="backend/.env"

cd "$(dirname "${BASH_SOURCE[0]}")"
REPO="$(pwd)"
LOG_DIR="$HOME/Library/Logs"
ARENA_LABEL="com.claudehq.arena"
TUNNEL_LABEL="com.claudehq.arena-tunnel"
AGENTS="$HOME/Library/LaunchAgents"

banner "Claude HQ Arena — host it on this Mac"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "This Mac will run the Arena server; Cloudflare will publish it safely."
note "No port forwarding, no router changes, no inbound holes in your firewall."
printf '\n'
for tool in uv python3 curl; do
  if command -v "$tool" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$tool"
  else
    printf '  %s✗%s %s — install it, then re-run\n' "$RED" "$RESET" "$tool"; exit 1
  fi
done

if command -v cloudflared >/dev/null 2>&1; then
  printf '  %s✓%s cloudflared (%s)\n' "$GREEN" "$RESET" "$(cloudflared --version 2>&1 | head -1)"
else
  warn "cloudflared is not installed."
  if command -v brew >/dev/null 2>&1; then
    if confirm "Install it now with Homebrew?"; then
      brew install cloudflared
    else
      SKIPPED+=("install cloudflared (brew install cloudflared)"); exit 1
    fi
  else
    say "Install it from https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/"
    exit 1
  fi
fi

printf '\n'
say "Installing backend dependencies."
( cd backend && uv sync --quiet )
printf '  %s✓%s dependencies ready\n' "$GREEN" "$RESET"
pause "Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare — authorise this machine"
say "You need a domain on Cloudflare (the free plan is fine)."
note "The tunnel needs a fixed hostname because GitHub OAuth callbacks"
note "must point at a URL that never changes."
printf '\n'
if [[ -f "$HOME/.cloudflared/cert.pem" ]]; then
  printf '  %s✓%s this machine is already authorised with Cloudflare\n' "$GREEN" "$RESET"
else
  step "A browser will open. Pick the domain you want to use and click Authorize."
  pause "Press Enter to run 'cloudflared tunnel login'"
  cloudflared tunnel login
fi
pause "Press Enter to continue"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare — create the tunnel"
say "Choose the public hostname your friends' dashboards will publish to."
note "It must be on the domain you just authorised, e.g. arena.yourdomain.com"
printf '\n'
ask ARENA_HOSTNAME "Public hostname:"
if [[ -z "$ARENA_HOSTNAME" || "$ARENA_HOSTNAME" != *.* ]]; then
  warn "That does not look like a hostname."; exit 1
fi
ARENA_HOSTNAME="${ARENA_HOSTNAME#http://}"; ARENA_HOSTNAME="${ARENA_HOSTNAME#https://}"
ARENA_HOSTNAME="${ARENA_HOSTNAME%%/*}"
APP_URL="https://${ARENA_HOSTNAME}"
write_env ARENA_HOSTNAME "$ARENA_HOSTNAME"
write_env ARENA_PUBLIC_BASE_URL "$APP_URL"

TUNNEL_NAME="claude-hq-arena"
printf '\n'
if cloudflared tunnel list 2>/dev/null | grep -qE "[[:space:]]${TUNNEL_NAME}[[:space:]]"; then
  printf '  %s✓%s tunnel %s already exists\n' "$GREEN" "$RESET" "$TUNNEL_NAME"
else
  cloudflared tunnel create "$TUNNEL_NAME"
fi
TUNNEL_ID=$(cloudflared tunnel list --output json 2>/dev/null \
  | python3 -c "import json,sys;print(next((t['id'] for t in json.load(sys.stdin) if t['name']=='$TUNNEL_NAME'),''))")
if [[ -z "$TUNNEL_ID" ]]; then warn "Could not determine the tunnel id."; exit 1; fi
printf '  %s✓%s tunnel id %s\n' "$GREEN" "$RESET" "$TUNNEL_ID"

say "Pointing $ARENA_HOSTNAME at the tunnel."
cloudflared tunnel route dns "$TUNNEL_NAME" "$ARENA_HOSTNAME" 2>&1 | tail -2 || \
  note "(route already exists — fine)"

python3 - "$TUNNEL_ID" "$ARENA_HOSTNAME" "$HOME" <<'PY'
import sys, pathlib
tid, host, home = sys.argv[1], sys.argv[2], sys.argv[3]
cfg = pathlib.Path(home) / ".cloudflared" / "config.yml"
cfg.write_text(
    f"tunnel: {tid}\n"
    f"credentials-file: {home}/.cloudflared/{tid}.json\n"
    "\n"
    "ingress:\n"
    f"  - hostname: {host}\n"
    "    service: http://127.0.0.1:8080\n"
    "    originRequest:\n"
    "      # Websocket rooms hold long-lived connections; do not cut them short.\n"
    "      noTLSVerify: false\n"
    "      connectTimeout: 30s\n"
    "  - service: http_status:404\n"
)
print(f"  wrote {cfg}")
PY
pause "Press Enter to continue"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "GitHub — OAuth app"
say "This is how you and your friends sign in to the Arena."
open_url "https://github.com/settings/applications/new"
step "Application name:  Claude HQ Arena"
step "Homepage URL:      $APP_URL"
step "Authorization callback URL — must match EXACTLY:"
printf '\n      %s%s/v1/auth/github/callback%s\n\n' "$BOLD" "$APP_URL" "$RESET"
step "Register application, copy the Client ID, then generate and copy a client secret."
warn "The client secret is shown only once."
printf '\n'
ask ARENA_GITHUB_CLIENT_ID "Paste the Client ID:"
ask_secret ARENA_GITHUB_CLIENT_SECRET "Paste the Client secret:"
write_env ARENA_GITHUB_CLIENT_ID "$ARENA_GITHUB_CLIENT_ID"
write_env ARENA_GITHUB_CLIENT_SECRET "$ARENA_GITHUB_CLIENT_SECRET"
pause "Press Enter to continue"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Configure the server"
say "Self-hosting uses SQLite — one file, nothing else to run or back up."
DB_PATH="$REPO/backend/arena.db"
# Four slashes: sqlite+aiosqlite://// means an absolute path. launchd starts
# the service with a different working directory, so a relative path would
# silently create a second, empty database.
write_env ARENA_DATABASE_URL "sqlite+aiosqlite:////${DB_PATH#/}"

ARENA_SECRET_KEY=$(_existing ARENA_SECRET_KEY || true)
if [[ -n "$ARENA_SECRET_KEY" ]]; then
  say "Reusing the existing signing key."
  note "Regenerating it would invalidate outstanding pairing codes."
else
  ARENA_SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")
fi
write_env ARENA_SECRET_KEY "$ARENA_SECRET_KEY"
chmod 600 "$ENV_FILE"
printf '  %s✓%s %s is readable only by you\n' "$GREEN" "$RESET" "$ENV_FILE"

say "Creating the database schema."
( cd backend && uv run --no-dev alembic upgrade head >/dev/null 2>&1 ) && \
  printf '  %s✓%s migrations applied\n' "$GREEN" "$RESET" || \
  warn "Migrations failed — check: cd backend && uv run alembic upgrade head"
pause "Press Enter to continue"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Run it in the background"
say "Two launchd agents: the Arena server, and the Cloudflare tunnel."
note "Both restart automatically if they crash or when you log back in."
mkdir -p "$AGENTS" "$LOG_DIR"

UV_BIN="$(command -v uv)"
CFD_BIN="$(command -v cloudflared)"

python3 - "$AGENTS" "$REPO" "$UV_BIN" "$CFD_BIN" "$LOG_DIR" "$ARENA_LABEL" "$TUNNEL_LABEL" <<'PY'
import pathlib, sys
agents, repo, uv, cfd, logs, arena_label, tunnel_label = sys.argv[1:8]

def plist(label, program_args, workdir):
    args = "\n".join(f"    <string>{a}</string>" for a in program_args)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>{label}</string>
  <key>ProgramArguments</key>
  <array>
{args}
  </array>
  <key>WorkingDirectory</key><string>{workdir}</string>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>{logs}/{label}.log</string>
  <key>StandardErrorPath</key><string>{logs}/{label}.err.log</string>
  <key>ProcessType</key><string>Background</string>
</dict>
</plist>
"""

a = pathlib.Path(agents)
(a / f"{arena_label}.plist").write_text(plist(
    arena_label,
    [uv, "run", "--no-dev", "uvicorn", "app.main:app",
     "--host", "127.0.0.1", "--port", "8080"],
    f"{repo}/backend"))
(a / f"{tunnel_label}.plist").write_text(plist(
    tunnel_label,
    [cfd, "tunnel", "run", "claude-hq-arena"],
    repo))
print(f"  wrote {arena_label}.plist and {tunnel_label}.plist")
PY

for label in "$ARENA_LABEL" "$TUNNEL_LABEL"; do
  launchctl bootout "gui/$(id -u)/$label" 2>/dev/null || true
  launchctl bootstrap "gui/$(id -u)" "$AGENTS/$label.plist" 2>/dev/null || \
    launchctl load "$AGENTS/$label.plist" 2>/dev/null || true
  printf '  %s✓%s started %s\n' "$GREEN" "$RESET" "$label"
done
say "Waiting for both to come up…"
sleep 6
pause "Press Enter to verify"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Verify"
say "Checking the server locally, then over the public hostname."
LOCAL=$(curl -fsS --max-time 5 http://127.0.0.1:8080/health 2>/dev/null || true)
if [[ -n "$LOCAL" ]]; then
  printf '  %s✓%s local:  %s\n' "$GREEN" "$RESET" "$LOCAL"
else
  warn "The server is not answering on 127.0.0.1:8080"
  note "Logs: tail -f $LOG_DIR/$ARENA_LABEL.err.log"
  SKIPPED+=("Arena server did not start")
fi

PUBLIC=""
for attempt in 1 2 3 4 5 6; do
  PUBLIC=$(curl -fsS --max-time 10 "$APP_URL/health" 2>/dev/null || true)
  [[ -n "$PUBLIC" ]] && break
  note "DNS/tunnel not ready yet (attempt $attempt/6) — waiting 10s"
  sleep 10
done
if [[ -n "$PUBLIC" ]]; then
  printf '  %s✓%s public: %s\n' "$GREEN" "$RESET" "$PUBLIC"
else
  warn "No response from $APP_URL/health"
  note "DNS can take a few minutes the first time. Then check:"
  note "  tail -f $LOG_DIR/$TUNNEL_LABEL.err.log"
  SKIPPED+=("public hostname did not respond — retry curl $APP_URL/health")
fi

printf '\n'
warn "Your Mac must be awake for friends to see the board."
note "Sleeping is not destructive: publishes retry every 5 minutes and each"
note "one carries a 30-day window, so nothing is lost — the board is just"
note "unreachable until you are back. To keep it up while plugged in:"
note "  System Settings → Lock Screen → turn display off… / Energy"
note "  or run:  caffeinate -s"
printf '\n'
say "Now connect your own dashboard:"
step "Claude HQ → 🏆 Arena → server URL:  $APP_URL"
step "Sign in with GitHub, paste the pairing code."
printf '\n'
say "Send your friends exactly this:"
printf '\n'
printf '    %sInstall Claude HQ, open the 🏆 Arena tab, enter:%s\n' "$DIM" "$RESET"
printf '    %s%s%s\n' "$BOLD" "$APP_URL" "$RESET"
printf '    %sthen Sign in with GitHub and paste the code back.%s\n' "$DIM" "$RESET"
printf '\n'
pause "Press Enter to finish"

finish
printf '  %sArena:%s   %s\n' "$BOLD" "$RESET" "$APP_URL"
printf '  %sLogs:%s    tail -f %s/%s.err.log\n' "$DIM" "$RESET" "$LOG_DIR" "$ARENA_LABEL"
printf '  %sRestart:%s launchctl kickstart -k gui/$(id -u)/%s\n' "$DIM" "$RESET" "$ARENA_LABEL"
printf '  %sStop:%s    launchctl bootout gui/$(id -u)/%s\n' "$DIM" "$RESET" "$ARENA_LABEL"
printf '\n'
