CREATE TABLE IF NOT EXISTS prestige (user_id VARCHAR(36) PRIMARY KEY, stars INTEGER NOT NULL DEFAULT 0, xp_base INTEGER NOT NULL DEFAULT 0, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS prestige_log (user_id VARCHAR(36) NOT NULL, star INTEGER NOT NULL, xp_at INTEGER NOT NULL, at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id, star));
