//! The creature battle rules duel plays out. No Valley hooks of its own.
//!
//! A port of `backend/app/pokebattle.py`, which is itself "a line-for-line
//! mirror of the engine in games/pokebattle.js". Everything a battler is -- its
//! level, stats, types, move list, PP and every damage number -- is derived HERE
//! from the vendored `app/data/pokemon.json`; a client only ever sends
//! `{sp, st, br, mg, sh, name}` per creature and a move-or-switch choice, so
//! nothing on the wire can inflate a stat. [`clean_spec`] is the gate that makes
//! that true.
//!
//! Both ports draw randomness only through one `rng() -> [0, 1)` IN THE SAME
//! ORDER, which is why [`Draw`] is a closure the caller owns rather than an
//! `StdRng`: duel.rs hands it `|| cx.rng.gen()`, and the tests below hand it the
//! constant 0.5 that `backend/tests/test_valley.py`'s `FixedRng` uses, so the
//! Python test's "no crits, no misses below 50% accuracy, damage roll 93, side b
//! wins ties" carries over unchanged. See divergence 2 in `super`'s module doc
//! for why no SEEDED Python sequence is reproducible in Rust.
//!
//! Audience: none. This module never touches [`super::Out`]; it returns event
//! lists and duel.rs decides who hears them.
//!
//! The data file is read at COMPILE time with `include_str!` -- the same file
//! the Python reads -- exactly as kart.rs:75, platformer.rs:85 and fps.rs:121
//! already do with theirs, so the binary cannot start with a missing or
//! half-written catalog.

use super::{floordiv, half_up};
use serde::Deserialize;
use serde_json::{json, Map, Value};
use std::collections::HashMap;
use std::sync::LazyLock;

/// `app/data/pokemon.json`, generated by `tools/build_pokedata.mjs` from Pokemon
/// Showdown (MIT) and byte-identical to `games/pokedata.js`.
pub const DATA_JSON: &str = include_str!("../../../backend/app/data/pokemon.json");

// ------------------------------------------------------------------- data --
// Typed rather than a `serde_json::Value` tree, because every lookup in this
// file is by a key the Python indexes with `[]` -- a missing one is a bug, not a
// branch -- and a typed struct turns that into one panic at startup instead of
// 40 silent `unwrap_or` defaults. Unknown fields (`num`, `forme`, a move's
// `name`) are simply not read, as the Python does not read them either.

#[derive(Deserialize)]
pub struct Data {
    /// Level per stage 0..4, Python's `DATA["levels"]`.
    pub levels: Vec<i64>,
    /// One evolution line per species slot: the national dex numbers in order.
    pub lines: Vec<Vec<i64>>,
    /// species slot (as a string) -> the dex numbers a final stage may branch to.
    pub branches: HashMap<String, Vec<i64>>,
    /// dex number (as a string) -> the mega keys it may use.
    #[serde(rename = "megaFor")]
    pub mega_for: HashMap<String, Vec<String>>,
    /// dex number (as a string) -> pokemon id.
    #[serde(rename = "byDex")]
    pub by_dex: HashMap<String, String>,
    /// mega key -> pokemon id.
    pub megas: HashMap<String, String>,
    /// attacking type -> defending type -> multiplier. A missing pair is 1.
    pub chart: HashMap<String, HashMap<String, f64>>,
    pub pokemon: HashMap<String, Species>,
    pub moves: HashMap<String, Move>,
}

#[derive(Deserialize)]
pub struct Species {
    pub name: String,
    pub types: Vec<String>,
    pub bs: Base,
    /// level (as a string) -> the four move ids known at it.
    pub moves: HashMap<String, Vec<String>>,
    /// Only the alternate formes carry one; `e.get("sprite")` is None otherwise
    /// and the key still reaches the wire as null.
    #[serde(default)]
    pub sprite: Option<i64>,
}

#[derive(Deserialize)]
pub struct Base {
    pub hp: i64,
    pub atk: i64,
    pub def: i64,
    pub spa: i64,
    pub spd: i64,
    pub spe: i64,
}

#[derive(Deserialize)]
pub struct Move {
    #[serde(rename = "type")]
    pub mtype: String,
    /// "physical", "special" or "status".
    pub cat: String,
    pub bp: i64,
    /// 0 means "never misses" -- the accuracy roll is skipped entirely.
    pub acc: i64,
    pub pp: i64,
    pub pri: i64,
    #[serde(default)]
    pub sec: Option<Sec>,
    /// stat -> stages. Read in [`BOOSTS`] order, never the map's own order.
    #[serde(default)]
    pub boosts: Option<HashMap<String, i64>>,
    /// `1` means the move targets its user. Python tests `mv.get("self") == 1`.
    #[serde(rename = "self", default)]
    pub self_: Option<i64>,
    #[serde(default)]
    pub crit: Option<i64>,
    #[serde(default)]
    pub recoil: Option<[i64; 2]>,
    #[serde(default)]
    pub drain: Option<[i64; 2]>,
    #[serde(default)]
    pub heal: Option<[i64; 2]>,
    #[serde(default)]
    pub status: Option<String>,
    /// "level" for Night Shade: damage is the user's level, no crit, no roll.
    #[serde(default)]
    pub fixed: Option<String>,
    /// Struggle's recoil flag.
    #[serde(default)]
    pub struggle: Option<i64>,
}

#[derive(Deserialize)]
pub struct Sec {
    pub chance: i64,
    #[serde(default)]
    pub status: Option<String>,
    #[serde(default)]
    pub boosts: Option<HashMap<String, i64>>,
    #[serde(rename = "volatileStatus", default)]
    pub volatile_status: Option<String>,
    #[serde(rename = "self", default)]
    pub self_: Option<SecSelf>,
}

#[derive(Deserialize)]
pub struct SecSelf {
    pub boosts: HashMap<String, i64>,
}

/// Python's module-level `DATA`. Parsed once, on first use.
pub static DATA: LazyLock<Data> =
    LazyLock::new(|| serde_json::from_str(DATA_JSON).expect("app/data/pokemon.json parses"));

/// Python's `MOVES[mid]`. Panics on an id outside the catalog, as the Python's
/// `KeyError` does; every caller takes its id from the same catalog.
pub fn move_of(id: &str) -> &'static Move {
    DATA.moves.get(id).unwrap_or_else(|| panic!("no move {id} in pokemon.json"))
}

// -------------------------------------------------------------- catalogs --

/// Python's `STATS`: the five stats `calc_stat` derives beside hp.
// [`build_mon`] names the five fields of [`MonStats`] directly rather than
// looping this, so nothing outside the test that pins it reads it. Kept because
// it is the order the Python's stats dict is built in, and a reviewer comparing
// the two files looks for it. (The module-wide allow in `super` covers this
// today; the targeted one keeps the file clean when that comes off.)
#[allow(dead_code)]
pub const STATS: [&str; 5] = ["atk", "def", "spa", "spd", "spe"];

/// Python's `BOOSTS`, and the ORDER a mon's `boosts` object reaches the wire in
/// ([`view_mon`]). Also the index order of [`Mon::boosts`].
pub const BOOSTS: [&str; 7] = ["atk", "def", "spa", "spd", "spe", "accuracy", "evasion"];

/// Index into [`Mon::boosts`], or None for a stat that is not boostable. A
/// move's `boosts` map is read through [`BOOSTS`], so an unknown key there is
/// skipped exactly as Python's `if stat not in boosts: continue` skips it.
pub fn boost_i(stat: &str) -> Option<usize> {
    BOOSTS.iter().position(|s| *s == stat)
}

const B_ACCURACY: usize = 5;
const B_EVASION: usize = 6;

/// Python's `CRIT_CHANCE`. Reached only for stages 1..3; a stage of 4 or more
/// short-circuits to "always a crit" before this is asked, which is why the
/// Python can index a three-key dict without a KeyError.
pub fn crit_chance(stage: i64) -> f64 {
    match stage {
        1 => 1.0 / 24.0,
        2 => 1.0 / 8.0,
        3 => 1.0 / 2.0,
        _ => panic!("crit stage {stage} is outside CRIT_CHANCE"),
    }
}

/// Python's `STATUS_IMMUNE`: the types each status cannot be inflicted on.
/// "slp" has an empty tuple and must still be a KEY -- `set_status` indexes this
/// unconditionally.
pub const STATUS_IMMUNE: [(&str, &[&str]); 5] = [
    ("par", &["Electric"]),
    ("brn", &["Fire"]),
    ("psn", &["Poison", "Steel"]),
    ("tox", &["Poison", "Steel"]),
    ("slp", &[]),
];

fn immune_types(status: &str) -> &'static [&'static str] {
    STATUS_IMMUNE
        .iter()
        .find(|(s, _)| *s == status)
        .unwrap_or_else(|| panic!("status {status} is not in STATUS_IMMUNE"))
        .1
}

/// One `rng() -> [0, 1)` draw, in the order both ports draw them. See the
/// module doc.
pub type Draw<'a> = &'a mut dyn FnMut() -> f64;

// ------------------------------------------------------------ the battlers --

/// Python's `_int(v)`: a Python int, and never a bool. serde_json keeps the
/// distinction the JSON document makes, so `4` is an integer and `4.0` is not --
/// `test_duel_team_validation_mega_and_branch` pins `{"sp": 1, "st": 4.0}` as
/// rejected, which is the whole point of the check.
///
/// Divergence: an integer above `i64::MAX` saturates to `i64::MAX` instead of
/// staying exact. Every caller then either range-rejects it (`sp`, `to`, `i`) or
/// clamps it (`st`), which is what the Python does with the exact value too.
fn py_int(v: Option<&Value>) -> Option<i64> {
    let n = v?.as_number()?;
    if n.is_f64() {
        return None; // a float is not an int, however round it looks
    }
    n.as_i64().or(Some(i64::MAX))
}

/// One creature as a client may describe it. Python's `clean_spec` result.
#[derive(Clone, Debug, PartialEq)]
pub struct Spec {
    pub sp: usize,
    /// Already clamped to 0..=4: a stage outside it is never trusted.
    pub st: i64,
    pub br: Option<i64>,
    pub mg: Option<String>,
    pub sh: bool,
    /// The client's nickname, printable-stripped and cut to 24 characters.
    /// [`build_mon`] does not read it -- it names the battler from the data file
    /// -- and `test_duel_team_validation_mega_and_branch` pins that a 99
    /// character "name" still comes back as "Raichu". Kept because it is part of
    /// `clean_spec`'s contract with the page.
    #[allow(dead_code)] // parsed exactly as the Python parses it, and read only by its test
    pub name: String,
}

/// One move slot of a battler: its id and its remaining PP.
#[derive(Clone, Debug, PartialEq)]
pub struct Slot {
    pub id: String,
    pub pp: i64,
    pub max: i64,
}

/// The five battle stats plus hp, Python's `mon["stats"]`. Never serialised: the
/// page is told hp and max, and derives nothing itself.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct MonStats {
    pub hp: i64,
    pub atk: i64,
    pub def: i64,
    pub spa: i64,
    pub spd: i64,
    pub spe: i64,
}

impl MonStats {
    /// Python's `mon["stats"][key]`. Panics on a key outside [`STATS`] plus hp.
    pub fn get(&self, k: &str) -> i64 {
        match k {
            "hp" => self.hp,
            "atk" => self.atk,
            "def" => self.def,
            "spa" => self.spa,
            "spd" => self.spd,
            "spe" => self.spe,
            _ => panic!("no stat {k}"),
        }
    }
}

/// Everything about one battler. Python's `build_mon` dict.
#[derive(Clone, Debug, PartialEq)]
pub struct Mon {
    pub name: String,
    /// The pokemon id in `DATA["pokemon"]` -- `mon["id"]` on the wire.
    pub id: String,
    pub dex: i64,
    pub sprite: Option<i64>,
    pub mega: Option<String>,
    pub shiny: bool,
    pub sp: i64,
    pub st: i64,
    pub lvl: i64,
    pub types: Vec<String>,
    pub stats: MonStats,
    pub hp: i64,
    pub max: i64,
    /// "par", "brn", "psn", "tox" or "slp".
    pub status: Option<String>,
    /// Turns of sleep left.
    pub slp: i64,
    /// Toxic's ramp, 0..=15.
    pub tox: i64,
    pub flinch: bool,
    /// In [`BOOSTS`] order, each -6..=6.
    pub boosts: [i64; 7],
    pub moves: Vec<Slot>,
}

/// Python's `evo_pos`: where in a line a stage lands. Uses [`half_up`] and not
/// Python's `round`, because `round(0.5)` would say 0 where JS `Math.round`
/// says 1 and the two engines must agree.
pub fn evo_pos(stage: i64, length: usize) -> usize {
    let n = length as i64;
    half_up(stage as f64 / 4.0 * (n - 1) as f64).clamp(0, n - 1) as usize
}

/// Python's `eff(atk, dfn)`: the chart entry, or 1 for a pair it does not list.
pub fn eff(atk: &str, dfn: &str) -> f64 {
    DATA.chart.get(atk).and_then(|row| row.get(dfn)).copied().unwrap_or(1.0)
}

/// Python's `type_mult`: the product over the defender's types.
pub fn type_mult(move_type: &str, types: &[String]) -> f64 {
    let mut m = 1.0;
    for t in types {
        m *= eff(move_type, t);
    }
    m
}

/// Python's `calc_stat`: the main-series formula at 31 IVs and no EVs.
pub fn calc_stat(base: i64, level: i64, hp: bool) -> i64 {
    let core = floordiv((2 * base + 31) * level, 100);
    if hp {
        core + level + 10
    } else {
        core + 5
    }
}

/// Python's `clean_spec`: one creature as a client may describe it, or None for
/// anything else. The stage is CLAMPED and the species is range-checked, so no
/// value past here can index outside the data file.
pub fn clean_spec(raw: &Value) -> Option<Spec> {
    let o = raw.as_object()?; // `not isinstance(raw, dict)`
    let sp = py_int(o.get("sp"))?;
    if !(0 <= sp && (sp as usize) < DATA.lines.len()) {
        return None;
    }
    let st = py_int(o.get("st"))?;
    let st = st.clamp(0, 4); // a stage outside 0..4 is clamped, never trusted
    let br = py_int(o.get("br"));
    let mg = o.get("mg").and_then(Value::as_str).map(str::to_string);
    // Python: `raw.get("sh") is True or (_int(raw.get("sh")) and raw.get("sh") == 1)`.
    let sh = matches!(o.get("sh"), Some(Value::Bool(true))) || py_int(o.get("sh")) == Some(1);
    // Python's `raw.get("name", raw.get("n"))`: `n` is the fallback only when
    // the "name" KEY is absent, so an explicit `"name": null` does not fall
    // back. `super::clip` is `_clip`: strip unprintables, trim, then cut 24
    // CHARACTERS -- the same three steps in the same order as `clean_spec`.
    let name_v = if o.contains_key("name") { o.get("name") } else { o.get("n") };
    Some(Spec { sp: sp as usize, st, br, mg, sh, name: super::clip(name_v, 24) })
}

/// Python's `build_mon`: everything about a battler, derived from
/// (species, stage) plus the vendored data.
pub fn build_mon(spec: &Spec) -> Mon {
    let line = &DATA.lines[spec.sp];
    let pos = evo_pos(spec.st, line.len());
    let mut dex = line[pos];
    let mut mega: Option<String> = None;
    if pos == line.len() - 1 {
        // Only a final stage branches, and only a final stage at stage 4 megas.
        if let Some(opts) = DATA.branches.get(&spec.sp.to_string()) {
            if !opts.is_empty() {
                // Python: `spec.get("br") if spec.get("br") in opts else opts[0]`
                // -- a branch that is not this line's falls back to the first.
                dex = match spec.br {
                    Some(b) if opts.contains(&b) => b,
                    _ => opts[0],
                };
            }
        }
        if spec.st == 4 {
            if let Some(mg) = &spec.mg {
                let listed = DATA.mega_for.get(&dex.to_string());
                if listed.map(|v| v.contains(mg)).unwrap_or(false) {
                    mega = Some(mg.clone());
                }
            }
        }
    }
    let pid: &str = match &mega {
        Some(m) => &DATA.megas[m],
        None => &DATA.by_dex[&dex.to_string()],
    };
    let e = &DATA.pokemon[pid];
    let lvl = DATA.levels[spec.st as usize];
    let stats = MonStats {
        hp: calc_stat(e.bs.hp, lvl, true),
        atk: calc_stat(e.bs.atk, lvl, false),
        def: calc_stat(e.bs.def, lvl, false),
        spa: calc_stat(e.bs.spa, lvl, false),
        spd: calc_stat(e.bs.spd, lvl, false),
        spe: calc_stat(e.bs.spe, lvl, false),
    };
    Mon {
        name: e.name.clone(),
        id: pid.to_string(),
        dex,
        sprite: e.sprite,
        mega,
        shiny: spec.sh,
        sp: spec.sp as i64,
        st: spec.st,
        lvl,
        types: e.types.clone(),
        hp: stats.hp,
        max: stats.hp,
        stats,
        status: None,
        slp: 0,
        tox: 0,
        flinch: false,
        boosts: [0; 7],
        moves: e.moves[&lvl.to_string()]
            .iter()
            .map(|m| Slot { id: m.clone(), pp: move_of(m).pp, max: move_of(m).pp })
            .collect(),
    }
}

// ----------------------------------------------------------- the battle --

/// One side of a battle: its team and which slot is out.
#[derive(Clone, Debug, PartialEq)]
pub struct Side {
    pub team: Vec<Mon>,
    pub active: usize,
}

/// Python's battle state (`new_battle`).
#[derive(Clone, Debug, PartialEq)]
pub struct Battle {
    pub sides: [Side; 2],
    pub turn: i64,
    pub over: bool,
    /// The winning side, or None for a double knockout.
    pub winner: Option<usize>,
}

pub fn new_battle(team_a: Vec<Mon>, team_b: Vec<Mon>) -> Battle {
    Battle {
        sides: [Side { team: team_a, active: 0 }, Side { team: team_b, active: 0 }],
        turn: 1,
        over: false,
        winner: None,
    }
}

/// Python's `active(state, side)`.
pub fn active(st: &Battle, side: usize) -> &Mon {
    let s = &st.sides[side];
    &s.team[s.active]
}

/// Python's `alive(state, side)`: the slots with hp left, in team order.
pub fn alive(st: &Battle, side: usize) -> Vec<usize> {
    st.sides[side]
        .team
        .iter()
        .enumerate()
        .filter(|(_, m)| m.hp > 0)
        .map(|(i, _)| i)
        .collect()
}

/// Python's `needs_replace`: the sides whose active has fainted and who still
/// have someone to send in. Empty once the battle is over.
pub fn needs_replace(st: &Battle) -> Vec<usize> {
    if st.over {
        return Vec::new();
    }
    (0..2).filter(|&i| active(st, i).hp <= 0 && !alive(st, i).is_empty()).collect()
}

/// A normalised action. Python's `{"k": "move", "i": i}`,
/// `{"k": "switch", "to": to}` and `{"k": "struggle"}`. Never serialised.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Act {
    Move(usize),
    Switch(usize),
    Struggle,
}

/// Python's `legal`: a normalised action, or None. A side that is out of PP
/// always Struggles, and ONLY for a "move" or "struggle" key -- any other key
/// is refused.
pub fn legal(st: &Battle, side: usize, act: Option<&Value>) -> Option<Act> {
    if st.over {
        return None;
    }
    let o = act?.as_object()?; // `not isinstance(act, dict)`
    let s = &st.sides[side];
    let mon = &s.team[s.active];
    let k = o.get("k").and_then(Value::as_str);
    if k == Some("switch") {
        let to = py_int(o.get("to"))?;
        let ok = 0 <= to
            && (to as usize) < s.team.len()
            && to as usize != s.active
            && s.team[to as usize].hp > 0;
        return ok.then_some(Act::Switch(to as usize));
    }
    if mon.hp <= 0 {
        return None;
    }
    if mon.moves.iter().all(|m| m.pp <= 0) {
        return matches!(k, Some("move") | Some("struggle")).then_some(Act::Struggle);
    }
    let i = py_int(o.get("i"))?;
    let ok = k == Some("move")
        && 0 <= i
        && (i as usize) < mon.moves.len()
        && mon.moves[i as usize].pp > 0;
    ok.then_some(Act::Move(i as usize))
}

/// Python's `auto_act`: the server's pick for an absent player -- the first move
/// with PP, or Struggle.
pub fn auto_act(st: &Battle, side: usize) -> Act {
    let mon = active(st, side);
    for (i, m) in mon.moves.iter().enumerate() {
        if m.pp > 0 {
            return Act::Move(i);
        }
    }
    Act::Struggle
}

/// Python's `stage_mult_stat`: the main-series stage multiplier, as integer
/// arithmetic.
pub fn stage_mult_stat(stat: i64, s: i64) -> i64 {
    floordiv(stat * (2 + s).max(2), (2 - s).max(2))
}

/// Python's `speed`: the boosted speed, halved by paralysis.
pub fn speed(mon: &Mon) -> i64 {
    let v = stage_mult_stat(mon.stats.spe, mon.boosts[boost_i("spe").unwrap()]);
    if mon.status.as_deref() == Some("par") {
        floordiv(v, 2)
    } else {
        v
    }
}

/// Python's `damage`: (damage, type multiplier) with the main-series formula;
/// `roll` is 85..=100. The multiplier is returned even when it is 0, because the
/// caller turns that into an "immune" event rather than a 0-damage hit.
pub fn damage(att: &Mon, dfn: &Mon, mv: &Move, crit: bool, roll: i64) -> (i64, f64) {
    let mult = if mv.mtype == "???" { 1.0 } else { type_mult(&mv.mtype, &dfn.types) };
    if mult == 0.0 {
        return (0, 0.0);
    }
    if mv.fixed.as_deref() == Some("level") {
        return (att.lvl, mult);
    }
    let phys = mv.cat == "physical";
    let (a_key, d_key) = if phys { ("atk", "def") } else { ("spa", "spd") };
    let (mut a_b, mut d_b) = (att.boosts[boost_i(a_key).unwrap()], dfn.boosts[boost_i(d_key).unwrap()]);
    if crit {
        // A crit ignores the attacker's drops and the defender's boosts.
        a_b = a_b.max(0);
        d_b = d_b.min(0);
    }
    let a = stage_mult_stat(att.stats.get(a_key), a_b);
    let d = stage_mult_stat(dfn.stats.get(d_key), d_b);
    let mut base = floordiv(floordiv((floordiv(2 * att.lvl, 5) + 2) * mv.bp * a, d), 50) + 2;
    if crit {
        base = (base as f64 * 1.5).floor() as i64;
    }
    base = floordiv(base * roll, 100);
    if att.types.contains(&mv.mtype) {
        base = (base as f64 * 1.5).floor() as i64; // same-type attack bonus
    }
    base = (base as f64 * mult).floor() as i64;
    if phys && att.status.as_deref() == Some("brn") {
        base = (base as f64 * 0.5).floor() as i64;
    }
    (base.max(1), mult)
}

// ------------------------------------------------------------------ turns --

/// Python's `_Turn`: one turn's mutations plus the event list they produced.
/// Every event is built with `json!` so its KEY ORDER is the Python's dict
/// order, which the page reads.
struct Turn<'a> {
    s: &'a mut Battle,
    rng: Draw<'a>,
    ev: Vec<Value>,
    /// Whether each side has already acted -- the flinch rule reads it.
    moved: [bool; 2],
}

impl Turn<'_> {
    fn mon(&self, side: usize) -> &Mon {
        active(self.s, side)
    }

    fn mon_mut(&mut self, side: usize) -> &mut Mon {
        let i = self.s.sides[side].active;
        &mut self.s.sides[side].team[i]
    }

    fn switch(&mut self, side: usize, to: usize) {
        {
            let old = self.mon_mut(side);
            old.boosts = [0; 7];
            old.flinch = false;
            if old.status.as_deref() == Some("tox") {
                old.tox = 0; // Toxic's ramp resets on a switch out
            }
        }
        self.s.sides[side].active = to;
        let name = self.mon(side).name.clone();
        self.ev.push(json!({"t": "switch", "side": side, "slot": to, "name": name}));
    }

    fn boosts(&mut self, side: usize, boosts: &HashMap<String, i64>) {
        for (bi, stat) in BOOSTS.iter().enumerate() {
            let Some(&want) = boosts.get(*stat) else { continue };
            let mon = self.mon_mut(side);
            let cur = mon.boosts[bi];
            let new = (cur + want).clamp(-6, 6);
            mon.boosts[bi] = new;
            let name = mon.name.clone();
            self.ev.push(json!({"t": "boost", "side": side, "name": name, "stat": stat,
                                "n": new - cur, "want": want}));
        }
    }

    fn set_status(&mut self, side: usize, status: &str, primary: bool) {
        let immune = immune_types(status);
        let (name, cur) = {
            let mon = self.mon(side);
            (mon.name.clone(), mon.status.clone())
        };
        let blocked = cur.is_some() || {
            let mon = self.mon(side);
            mon.types.iter().any(|t| immune.contains(&t.as_str()))
        };
        if blocked {
            // Only a PRIMARY status move says so; a secondary effect fails quietly.
            if primary {
                let why = if cur.is_some() { "already" } else { "immune" };
                self.ev.push(json!({"t": "fail", "side": side, "name": name, "why": why,
                                    "s": cur}));
            }
            return;
        }
        // The sleep length is the only draw in here, and it happens after the
        // immunity check, exactly as the Python's does.
        let slp = (status == "slp").then(|| 1 + ((self.rng)() * 3.0).floor() as i64);
        let mon = self.mon_mut(side);
        mon.status = Some(status.to_string());
        if let Some(n) = slp {
            mon.slp = n;
        }
        if status == "tox" {
            mon.tox = 0;
        }
        self.ev.push(json!({"t": "status", "side": side, "name": name, "s": status}));
    }

    fn heal(&mut self, side: usize, amount: i64, why: &str) {
        let (name, hp, max) = {
            let mon = self.mon_mut(side);
            mon.hp = (mon.hp + amount).min(mon.max);
            (mon.name.clone(), mon.hp, mon.max)
        };
        self.ev.push(json!({"t": "heal", "side": side, "name": name, "hp": hp, "max": max,
                            "why": why}));
    }

    fn hurt(&mut self, side: usize, amount: i64, why: &str) {
        let (name, hp, max) = {
            let mon = self.mon_mut(side);
            mon.hp = (mon.hp - amount).max(0);
            (mon.name.clone(), mon.hp, mon.max)
        };
        self.ev.push(json!({"t": "residual", "side": side, "name": name, "hp": hp, "max": max,
                            "why": why}));
        if hp <= 0 {
            self.ev.push(json!({"t": "faint", "side": side, "name": name}));
        }
    }

    fn cant(&mut self, side: usize, why: &str) {
        let name = self.mon(side).name.clone();
        self.ev.push(json!({"t": "cant", "side": side, "name": name, "why": why}));
    }

    fn use_move(&mut self, side: usize, act: Act) {
        let foe = 1 - side;
        if self.mon(side).hp <= 0 {
            return;
        }
        if self.mon(side).status.as_deref() == Some("slp") {
            if self.mon(side).slp > 0 {
                self.mon_mut(side).slp -= 1;
                self.cant(side, "slp");
                return;
            }
            self.mon_mut(side).status = None;
            let name = self.mon(side).name.clone();
            self.ev.push(json!({"t": "cure", "side": side, "name": name, "s": "slp"}));
        }
        if self.mon(side).flinch {
            self.cant(side, "flinch");
            return;
        }
        if self.mon(side).status.as_deref() == Some("par") && (self.rng)() < 0.25 {
            self.cant(side, "par");
            return;
        }
        // PP comes off here, before anything can miss or fail.
        let mid = match act {
            Act::Struggle => "struggle".to_string(),
            Act::Move(i) => {
                let mon = self.mon_mut(side);
                mon.moves[i].pp -= 1;
                mon.moves[i].id.clone()
            }
            Act::Switch(_) => panic!("use_move with a switch"),
        };
        let mv = move_of(&mid);
        let user = self.mon(side).name.clone();
        self.ev.push(json!({"t": "move", "side": side, "name": user, "move": mid}));
        let target_self = mv.self_ == Some(1);
        if !target_self && self.mon(foe).hp <= 0 {
            self.ev.push(json!({"t": "fail", "side": side, "name": user, "why": "notarget"}));
            return;
        }
        if !target_self && mv.acc > 0 {
            let s = (self.mon(side).boosts[B_ACCURACY] - self.mon(foe).boosts[B_EVASION])
                .clamp(-6, 6);
            let (num, den) = if s >= 0 { (3 + s, 3) } else { (3, 3 - s) };
            // Python's `if not self.rng() * 100 < mv["acc"] * num / den` -- a
            // TRUE float division, not an integer one. Written as `>=` rather
            // than the Python's negated `<` because clippy rejects `!(a < b)`
            // on a partial order; both sides here are finite (the draw is in
            // [0, 1) and acc/num/den are small positive integers), so the two
            // spellings cannot disagree.
            if (self.rng)() * 100.0 >= mv.acc as f64 * num as f64 / den as f64 {
                // The Python credits the miss to the FOE's side with the USER's
                // name; the page reads it as "whose attack missed".
                self.ev.push(json!({"t": "miss", "side": foe, "name": user}));
                return;
            }
        }
        if mv.cat == "status" {
            // heal, then boosts, then status: one branch only, as the Python's
            // if/elif chain does.
            if let Some(h) = mv.heal {
                if self.mon(side).hp >= self.mon(side).max {
                    self.ev
                        .push(json!({"t": "fail", "side": side, "name": user, "why": "fullhp"}));
                } else {
                    let max = self.mon(side).max;
                    let amount = half_up(max as f64 * h[0] as f64 / h[1] as f64);
                    self.heal(side, amount, "move");
                }
            } else if let Some(b) = &mv.boosts {
                self.boosts(if target_self { side } else { foe }, b);
            } else if let Some(s) = &mv.status {
                self.set_status(foe, s, true);
            }
            return;
        }
        let crit_stage = mv.crit.unwrap_or(1);
        let fixed_level = mv.fixed.as_deref() == Some("level");
        // Short-circuit order is load-bearing: a fixed-damage move draws
        // NEITHER the crit nor the roll, so the stream stays in step.
        let crit = !fixed_level && (crit_stage >= 4 || (self.rng)() < crit_chance(crit_stage));
        let roll = if fixed_level { 100 } else { 85 + ((self.rng)() * 16.0).floor() as i64 };
        let (dmg, mult) = damage(self.mon(side), self.mon(foe), mv, crit, roll);
        if mult == 0.0 {
            let name = self.mon(foe).name.clone();
            self.ev.push(json!({"t": "immune", "side": foe, "name": name}));
            return;
        }
        let dealt = dmg.min(self.mon(foe).hp);
        let (tname, thp, tmax) = {
            let tgt = self.mon_mut(foe);
            tgt.hp -= dealt;
            (tgt.name.clone(), tgt.hp, tgt.max)
        };
        self.ev.push(json!({"t": "dmg", "side": foe, "name": tname, "hp": thp, "max": tmax,
                            "eff": mult, "crit": crit, "move": mid}));
        if thp <= 0 {
            self.ev.push(json!({"t": "faint", "side": foe, "name": tname}));
        }
        if let Some(d) = mv.drain {
            if self.mon(side).hp < self.mon(side).max {
                let amount = half_up(dealt as f64 * d[0] as f64 / d[1] as f64).max(1);
                self.heal(side, amount, "drain");
            }
        }
        if let Some(sec) = &mv.sec {
            if (self.rng)() * 100.0 < sec.chance as f64 {
                if self.mon(foe).hp > 0 {
                    if let Some(s) = &sec.status {
                        self.set_status(foe, s, false);
                    }
                    if let Some(b) = &sec.boosts {
                        self.boosts(foe, b);
                    }
                    // A flinch only lands on someone who has not moved yet.
                    if sec.volatile_status.as_deref() == Some("flinch") && !self.moved[foe] {
                        self.mon_mut(foe).flinch = true;
                    }
                }
                if let Some(sf) = &sec.self_ {
                    self.boosts(side, &sf.boosts);
                }
            }
        }
        if mv.struggle.is_some() {
            let max = self.mon(side).max;
            self.hurt(side, half_up(max as f64 / 4.0).max(1), "recoil");
        } else if let Some(r) = mv.recoil {
            let amount = half_up(dealt as f64 * r[0] as f64 / r[1] as f64).max(1);
            self.hurt(side, amount, "recoil");
        }
    }

    /// Python's `order`: switches first, then priority, then speed, with a coin
    /// toss on an exact tie.
    fn order(&mut self, acts: &[Act; 2]) -> [usize; 2] {
        let (k0, k1) = {
            let key = |side: usize| -> (i64, i64, i64) {
                let mon = self.mon(side);
                match acts[side] {
                    Act::Switch(_) => (1, 0, speed(mon)),
                    Act::Struggle => (0, move_of("struggle").pri, speed(mon)),
                    Act::Move(i) => (0, move_of(&mon.moves[i].id).pri, speed(mon)),
                }
            };
            (key(0), key(1))
        };
        if k0 == k1 {
            // Python's `[0, 1] if self.rng() < 0.5 else [1, 0]`: side b wins the
            // tie on the 0.5 the test fixture always draws.
            return if (self.rng)() < 0.5 { [0, 1] } else { [1, 0] };
        }
        if k0 > k1 {
            [0, 1]
        } else {
            [1, 0]
        }
    }

    fn end_of_turn(&mut self) {
        for side in 0..2 {
            let (hp, max, status) = {
                let mon = self.mon(side);
                (mon.hp, mon.max, mon.status.clone())
            };
            if hp <= 0 {
                continue;
            }
            match status.as_deref() {
                Some("brn") => self.hurt(side, floordiv(max, 16).max(1), "brn"),
                Some("psn") => self.hurt(side, floordiv(max, 8).max(1), "psn"),
                Some("tox") => {
                    let tox = {
                        let mon = self.mon_mut(side);
                        mon.tox = (mon.tox + 1).min(15);
                        mon.tox
                    };
                    self.hurt(side, floordiv(max * tox, 16).max(1), "tox");
                }
                _ => {}
            }
        }
        for side in 0..2 {
            self.mon_mut(side).flinch = false;
        }
    }
}

/// Python's `_finish`: a side with nobody left ends the battle, and a double
/// knockout has no winner.
fn finish(st: &mut Battle, ev: &mut Vec<Value>) {
    let (a, b) = (!alive(st, 0).is_empty(), !alive(st, 1).is_empty());
    if !(a && b) {
        st.over = true;
        st.winner = if a {
            Some(0)
        } else if b {
            Some(1)
        } else {
            None
        };
        ev.push(json!({"t": "end", "winner": st.winner}));
    }
}

/// Python's `resolve_turn`: both sides' already-legal actions -> ordered events;
/// mutates `st`.
pub fn resolve_turn(st: &mut Battle, act_a: Act, act_b: Act, rng: Draw) -> Vec<Value> {
    let acts = [act_a, act_b];
    let mut ev = {
        let mut t = Turn { s: st, rng, ev: Vec::new(), moved: [false, false] };
        for side in t.order(&acts) {
            match acts[side] {
                Act::Switch(to) => t.switch(side, to),
                other => t.use_move(side, other),
            }
            t.moved[side] = true;
        }
        t.end_of_turn();
        t.ev
    };
    st.turn += 1;
    finish(st, &mut ev);
    ev
}

/// Python's `replace`: a side whose active fainted sends in `slot` (which must
/// be alive). The `_Turn` is built with a generator that always returns 0.0,
/// because a switch draws nothing.
pub fn replace(st: &mut Battle, side: usize, slot: usize) -> Vec<Value> {
    let mut never = || 0.0;
    let mut t = Turn { s: st, rng: &mut never, ev: Vec::new(), moved: [false, false] };
    t.switch(side, slot);
    t.ev
}

/// Python's `view_mon`: the fourteen keys the page is told about one battler,
/// IN THIS ORDER, plus its move slots. Note `stats` is NOT among them -- the
/// page is given hp and max and derives nothing.
pub fn view_mon(m: &Mon) -> Value {
    let mut boosts = Map::new();
    for (i, k) in BOOSTS.iter().enumerate() {
        boosts.insert((*k).to_string(), json!(m.boosts[i]));
    }
    json!({
        "name": m.name, "id": m.id, "dex": m.dex, "sprite": m.sprite, "mega": m.mega,
        "shiny": m.shiny, "sp": m.sp, "st": m.st, "lvl": m.lvl, "types": m.types,
        "hp": m.hp, "max": m.max, "status": m.status, "boosts": Value::Object(boosts),
        "moves": m.moves.iter()
            .map(|s| json!({"id": s.id, "pp": s.pp, "max": s.max}))
            .collect::<Vec<_>>(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `backend/tests/test_valley.py`'s `FixedRng`: every draw is 0.5. No crits
    /// (0.5 is above both 1/24 and 1/8), no misses below 50% accuracy, damage
    /// roll 93, and side b wins a speed tie.
    fn fixed() -> impl FnMut() -> f64 {
        || 0.5
    }

    /// The five creatures the Python duel tests use, by (species slot, stage).
    const CHARIZARD: (usize, i64) = (1, 4);
    const VENUSAUR: (usize, i64) = (3, 4);
    const PIKACHU18: (usize, i64) = (0, 1);
    const MAGIKARP: (usize, i64) = (14, 0);
    const GENGAR: (usize, i64) = (5, 4);

    fn spec(sp: usize, st: i64) -> Spec {
        Spec { sp, st, br: None, mg: None, sh: false, name: String::new() }
    }

    fn mon(c: (usize, i64)) -> Mon {
        build_mon(&spec(c.0, c.1))
    }

    fn evs(ev: &[Value], t: &str) -> Vec<Value> {
        ev.iter().filter(|e| e["t"] == t).cloned().collect()
    }

    // -------------------------------------------------------- the catalogs --

    #[test]
    fn the_data_file_parses_and_carries_the_tables_the_engine_indexes() {
        assert_eq!(DATA.levels, vec![8, 18, 30, 42, 55]);
        assert_eq!(DATA.lines.len(), 48);
        assert_eq!(STATS, ["atk", "def", "spa", "spd", "spe"]);
        assert_eq!(BOOSTS, ["atk", "def", "spa", "spd", "spe", "accuracy", "evasion"]);
        assert_eq!(crit_chance(1), 1.0 / 24.0);
        assert_eq!(crit_chance(2), 1.0 / 8.0);
        assert_eq!(crit_chance(3), 0.5);
        // "slp" has no immune type and must still be a key: set_status indexes
        // STATUS_IMMUNE unconditionally.
        assert_eq!(immune_types("slp"), &[] as &[&str]);
        assert_eq!(immune_types("par"), &["Electric"]);
        assert_eq!(immune_types("psn"), &["Poison", "Steel"]);
        assert_eq!(move_of("struggle").mtype, "???");
        assert_eq!(move_of("quickattack").pri, 1);
    }

    #[test]
    fn the_type_chart_defaults_to_one_for_a_pair_it_does_not_list() {
        assert_eq!(eff("Fire", "Grass"), 2.0);
        assert_eq!(eff("Fire", "Water"), 0.5);
        assert_eq!(eff("Normal", "Ghost"), 0.0);
        assert_eq!(eff("Normal", "Fire"), 1.0); // not in the chart at all
        assert_eq!(eff("???", "Fire"), 1.0); // Struggle's type is in no row
        // A double weakness multiplies: Fire is 2x Grass and 2x Bug.
        assert_eq!(type_mult("Fire", &["Grass".into(), "Bug".into()]), 4.0);
        assert_eq!(type_mult("Fire", &["Grass".into(), "Poison".into()]), 2.0);
    }

    #[test]
    fn evo_pos_rounds_half_up_the_way_js_math_round_does() {
        // A two-long line: stage 2 is 0.5 of the way, and `round(0.5)` would say
        // 0 where Math.round says 1.
        assert_eq!((0..=4).map(|s| evo_pos(s, 2)).collect::<Vec<_>>(), vec![0, 0, 1, 1, 1]);
        assert_eq!((0..=4).map(|s| evo_pos(s, 3)).collect::<Vec<_>>(), vec![0, 1, 1, 2, 2]);
        assert_eq!(evo_pos(99, 3), 2); // clamped to the last position
        assert_eq!(evo_pos(0, 1), 0);
    }

    // ------------------------------------------------------- the team gate --

    #[test]
    fn a_creature_the_client_describes_is_rebuilt_from_the_data_not_trusted() {
        // test_duel_stats_and_moves_are_derived_server_side: the client sends
        // inflated stats and a move it does not know, and gets Charizard.
        let raw = json!({"sp": 1, "st": 4, "hp": 9999, "max": 9999, "atk": 9999,
                         "stats": {"spe": 999}, "moves": ["hyperbeam"], "name": "Sparky"});
        let s = clean_spec(&raw).unwrap();
        assert_eq!(s.name, "Sparky"); // parsed, and then never read again
        let m = build_mon(&s);
        assert_eq!((m.name.as_str(), m.lvl, m.hp, m.max), ("Charizard", 55, 167, 167));
        assert_eq!(m.types, vec!["Fire", "Flying"]);
        assert_eq!(m.moves.iter().map(|x| x.id.as_str()).collect::<Vec<_>>(),
                   vec!["flareblitz", "dragonclaw", "airslash", "scaryface"]);
        assert_eq!(m.moves.iter().map(|x| x.pp).collect::<Vec<_>>(), vec![15, 15, 15, 10]);
        assert_eq!(m.stats.spe, 132);
        assert_eq!(m.id, "charizard");
        assert_eq!(m.dex, 6);
    }

    #[test]
    fn a_spec_needs_a_real_species_and_a_whole_number_stage() {
        assert!(clean_spec(&json!({"sp": true, "st": 4})).is_none()); // a bool is not an int
        assert!(clean_spec(&json!({"sp": 1, "st": 4.0})).is_none()); // 4.0 is not an int
        assert!(clean_spec(&json!({"sp": 48, "st": 0})).is_none()); // past the last line
        assert!(clean_spec(&json!({"sp": -1, "st": 0})).is_none());
        assert!(clean_spec(&json!({"sp": 1})).is_none()); // no stage at all
        assert!(clean_spec(&json!([1, 4])).is_none()); // not a dict
        // The stage is CLAMPED, never rejected: stage 5 is stage 4.
        assert_eq!(clean_spec(&json!({"sp": 1, "st": 5})).unwrap().st, 4);
        assert_eq!(clean_spec(&json!({"sp": 1, "st": -3})).unwrap().st, 0);
    }

    #[test]
    fn a_nickname_is_stripped_trimmed_and_cut_to_twenty_four_characters() {
        let name = |raw: Value| clean_spec(&raw).unwrap().name;
        assert_eq!(name(json!({"sp": 0, "st": 4, "name": "x".repeat(99)})), "x".repeat(24));
        assert_eq!(name(json!({"sp": 0, "st": 4, "name": "  Ash\tKetchum  "})), "AshKetchum");
        assert_eq!(name(json!({"sp": 0, "st": 4, "n": "Sparky"})), "Sparky");
        // Python's `raw.get("name", raw.get("n"))`: an explicit null "name" does
        // NOT fall back to "n".
        assert_eq!(name(json!({"sp": 0, "st": 4, "name": null, "n": "Sparky"})), "");
        assert_eq!(name(json!({"sp": 0, "st": 4, "name": 7})), "");
        assert_eq!(name(json!({"sp": 0, "st": 4})), "");
        // ... and the nickname never reaches the battler, which is the point.
        let m = build_mon(&clean_spec(&json!({"sp": 0, "st": 4, "name": "x".repeat(99)})).unwrap());
        assert_eq!(m.name, "Raichu");
    }

    #[test]
    fn shiny_is_true_or_the_integer_one_and_nothing_else() {
        let sh = |v: Value| clean_spec(&json!({"sp": 0, "st": 4, "sh": v})).unwrap().sh;
        assert!(sh(json!(true)));
        assert!(sh(json!(1)));
        assert!(!sh(json!(0)));
        assert!(!sh(json!(1.0))); // a float is not the int 1
        assert!(!sh(json!("true")));
        assert!(!sh(Value::Null));
        assert!(!clean_spec(&json!({"sp": 0, "st": 4})).unwrap().sh);
    }

    #[test]
    fn a_mega_needs_stage_four_and_has_to_be_its_own() {
        // test_duel_team_validation_mega_and_branch, line for line.
        let at = |st: i64, mg: &str| {
            build_mon(&Spec { sp: 1, st, br: None, mg: Some(mg.into()), sh: false,
                              name: String::new() })
        };
        assert_eq!(at(3, "charizard-megax").name, "Charizard"); // Mega only at stage 4
        let mega = at(4, "charizard-megax");
        assert_eq!((mega.name.as_str(), mega.mega.as_deref(), mega.sprite),
                   ("Mega Charizard X", Some("charizard-megax"), Some(10034)));
        assert_eq!(mega.types, vec!["Fire", "Dragon"]);
        assert!(at(4, "gengar-mega").mega.is_none()); // not Charizard's mega
    }

    #[test]
    fn a_final_stage_branch_falls_back_to_the_first_of_its_own() {
        let br = |st: i64, b: i64| {
            build_mon(&Spec { sp: 4, st, br: Some(b), mg: None, sh: false, name: String::new() })
                .name
        };
        assert_eq!(br(4, 197), "Umbreon");
        assert_eq!(br(4, 25), "Vaporeon"); // not an Eevee branch: the default
        assert_eq!(br(1, 197), "Eevee"); // not a final stage: no branch at all
        // No branch asked for at all still takes the first option.
        assert_eq!(build_mon(&spec(4, 4)).name, "Vaporeon");
    }

    #[test]
    fn calc_stat_is_the_main_series_formula_at_thirty_one_ivs() {
        // Charizard, level 55: hp 167 and speed 132 are what the Python test
        // pins through the wire.
        assert_eq!(calc_stat(78, 55, true), 167);
        assert_eq!(calc_stat(100, 55, false), 132);
        assert_eq!(calc_stat(10, 8, false), 9);
        assert_eq!(calc_stat(10, 8, true), 22);
    }

    // ----------------------------------------------------------- the rules --

    #[test]
    fn stage_multipliers_and_paralysis_halve_integer_arithmetic() {
        assert_eq!(stage_mult_stat(100, 0), 100);
        assert_eq!(stage_mult_stat(100, 1), 150);
        assert_eq!(stage_mult_stat(100, -1), 66); // 100 * 2 // 3, floored
        assert_eq!(stage_mult_stat(100, 6), 400);
        assert_eq!(stage_mult_stat(100, -6), 25);
        let mut zard = mon(CHARIZARD);
        assert_eq!(speed(&zard), 132);
        zard.status = Some("par".into());
        assert_eq!(speed(&zard), 66);
        zard.boosts[boost_i("spe").unwrap()] = 1;
        assert_eq!(speed(&zard), 99); // boost first, then the halving
    }

    #[test]
    fn damage_follows_the_formula_and_the_roll_bounds_the_hit() {
        // test_duel_simultaneous_choice_speed_damage_and_pp's assertions.
        let (zard, saur) = (mon(CHARIZARD), mon(VENUSAUR));
        let fb = move_of("flareblitz");
        let (want, mult) = damage(&zard, &saur, fb, false, 93);
        assert_eq!(mult, 2.0); // Fire on Grass/Poison
        assert!(1 <= want && want <= saur.max);
        let lo = damage(&zard, &saur, fb, false, 85).0;
        let hi = damage(&zard, &saur, fb, false, 100).0;
        assert!(lo <= want && want <= hi);
        // A crit is strictly harder, and a burn halves a physical hit.
        assert!(damage(&zard, &saur, fb, true, 93).0 > want);
        let mut burnt = zard.clone();
        burnt.status = Some("brn".into());
        assert!(damage(&burnt, &saur, fb, false, 93).0 < want);
        // Immunity comes back as a zero multiplier, not as zero damage.
        assert_eq!(damage(&mon(PIKACHU18), &mon(GENGAR), move_of("quickattack"), false, 93),
                   (0, 0.0));
        // Night Shade is the user's level, whatever the roll.
        let ns = move_of("nightshade");
        assert_eq!(damage(&zard, &saur, ns, false, 85).0, zard.lvl);
    }

    #[test]
    fn a_struggling_side_is_the_only_one_that_may_send_a_struggle() {
        let mut st = new_battle(vec![mon(CHARIZARD)], vec![mon(VENUSAUR)]);
        // With PP in the tank, "struggle" is not a legal key.
        assert_eq!(legal(&st, 0, Some(&json!({"k": "struggle"}))), None);
        assert_eq!(legal(&st, 0, Some(&json!({"k": "move", "i": 0}))), Some(Act::Move(0)));
        assert_eq!(auto_act(&st, 0), Act::Move(0));
        for m in &mut st.sides[0].team[0].moves {
            m.pp = 0;
        }
        // Out of PP, both keys Struggle and the move index is ignored.
        assert_eq!(legal(&st, 0, Some(&json!({"k": "struggle"}))), Some(Act::Struggle));
        assert_eq!(legal(&st, 0, Some(&json!({"k": "move", "i": 3}))), Some(Act::Struggle));
        assert_eq!(legal(&st, 0, Some(&json!({"k": "nope"}))), None);
        assert_eq!(auto_act(&st, 0), Act::Struggle);
    }

    #[test]
    fn legal_refuses_a_spent_move_a_bad_index_and_a_pointless_switch() {
        let mut st = new_battle(vec![mon(CHARIZARD), mon(MAGIKARP)], vec![mon(VENUSAUR)]);
        st.sides[0].team[0].moves[1].pp = 0;
        assert_eq!(legal(&st, 0, Some(&json!({"k": "move", "i": 1}))), None);
        assert_eq!(legal(&st, 0, Some(&json!({"k": "move", "i": 4}))), None);
        assert_eq!(legal(&st, 0, Some(&json!({"k": "move", "i": -1}))), None);
        assert_eq!(legal(&st, 0, Some(&json!({"k": "move", "i": 0.0}))), None); // not an int
        assert_eq!(legal(&st, 0, Some(&json!({"k": "move", "i": true}))), None);
        assert_eq!(legal(&st, 0, None), None);
        assert_eq!(legal(&st, 0, Some(&json!("move"))), None); // not a dict
        assert_eq!(legal(&st, 0, Some(&json!({"k": "switch", "to": 1}))), Some(Act::Switch(1)));
        assert_eq!(legal(&st, 0, Some(&json!({"k": "switch", "to": 0}))), None); // already out
        assert_eq!(legal(&st, 1, Some(&json!({"k": "switch", "to": 1}))), None); // no such slot
        st.sides[0].team[1].hp = 0;
        assert_eq!(legal(&st, 0, Some(&json!({"k": "switch", "to": 1}))), None); // fainted
        // A finished battle refuses everything, including a switch.
        st.over = true;
        assert_eq!(legal(&st, 0, Some(&json!({"k": "move", "i": 0}))), None);
        assert_eq!(legal(&st, 0, Some(&json!({"k": "switch", "to": 1}))), None);
    }

    #[test]
    fn the_faster_creature_moves_first_and_priority_beats_speed() {
        // test_duel_simultaneous_choice_... and
        // test_duel_priority_beats_speed_and_type_immunity.
        let mut st = new_battle(vec![mon(CHARIZARD)], vec![mon(VENUSAUR)]);
        let mut r = fixed();
        let ev = resolve_turn(&mut st, Act::Move(0), Act::Move(0), &mut r);
        let sides: Vec<_> = evs(&ev, "move").iter().map(|e| e["side"].as_i64().unwrap()).collect();
        assert_eq!(sides, vec![0, 1]); // Charizard 132 before Venusaur 110

        let mut st = new_battle(vec![mon(GENGAR)], vec![mon(PIKACHU18)]);
        assert_eq!(st.sides[1].team[0].moves[1].id, "quickattack");
        let mut r = fixed();
        let ev = resolve_turn(&mut st, Act::Move(0), Act::Move(1), &mut r);
        let first = &evs(&ev, "move")[0];
        assert_eq!((first["side"].as_i64().unwrap(), first["move"].as_str().unwrap()),
                   (1, "quickattack"));
        // ... and Normal does nothing at all to a Ghost.
        let hit = ev.iter().find(|e| e["side"] == 0 && (e["t"] == "dmg" || e["t"] == "immune"));
        assert_eq!(hit.unwrap()["t"], "immune");
    }

    #[test]
    fn an_exact_tie_is_broken_by_the_draw_and_side_b_wins_on_a_half() {
        let mut st = new_battle(vec![mon(VENUSAUR)], vec![mon(VENUSAUR)]);
        let mut r = fixed(); // 0.5 is not < 0.5, so [1, 0]
        let ev = resolve_turn(&mut st, Act::Move(0), Act::Move(0), &mut r);
        let sides: Vec<_> = evs(&ev, "move").iter().map(|e| e["side"].as_i64().unwrap()).collect();
        assert_eq!(sides, vec![1, 0]);
        // A draw under 0.5 flips it.
        let mut st = new_battle(vec![mon(VENUSAUR)], vec![mon(VENUSAUR)]);
        let mut low = || 0.1;
        let ev = resolve_turn(&mut st, Act::Move(0), Act::Move(0), &mut low);
        let sides: Vec<_> = evs(&ev, "move").iter().map(|e| e["side"].as_i64().unwrap()).collect();
        assert_eq!(sides, vec![0, 1]);
    }

    #[test]
    fn a_switch_goes_before_any_move_however_slow_the_switcher() {
        let mut st = new_battle(vec![mon(MAGIKARP), mon(MAGIKARP)], vec![mon(CHARIZARD)]);
        let mut r = fixed();
        let ev = resolve_turn(&mut st, Act::Switch(1), Act::Move(0), &mut r);
        assert_eq!(ev[0]["t"], "switch");
        assert_eq!(ev[0]["side"], 0);
    }

    #[test]
    fn pp_comes_off_the_slot_that_was_used_and_a_hit_fills_in_the_recoil() {
        let mut st = new_battle(vec![mon(CHARIZARD)], vec![mon(VENUSAUR)]);
        let saur_max = st.sides[1].team[0].max;
        let mut r = fixed();
        let ev = resolve_turn(&mut st, Act::Move(0), Act::Move(0), &mut r);
        assert_eq!(st.sides[0].team[0].moves[0].pp, 14);
        assert_eq!(st.sides[0].team[0].moves[1].pp, 15);
        let hit = ev.iter().find(|e| e["t"] == "dmg" && e["side"] == 1).unwrap();
        let want = damage(&mon(CHARIZARD), &mon(VENUSAUR), move_of("flareblitz"), false, 93).0;
        assert_eq!(hit["hp"], saur_max - want);
        assert_eq!(hit["crit"], false);
        assert_eq!(hit["eff"], 2.0);
        // Flare Blitz's recoil lands on its user.
        let recoil = ev.iter().find(|e| e["t"] == "residual" && e["why"] == "recoil").unwrap();
        assert_eq!(recoil["side"], 0);
        assert_eq!(st.turn, 2);
    }

    #[test]
    fn a_faint_asks_that_side_to_replace_and_the_last_one_ends_the_battle() {
        // test_duel_replace_phase_then_win's shape, without the sockets.
        let mut st = new_battle(vec![mon(CHARIZARD)], vec![mon(MAGIKARP), mon(MAGIKARP)]);
        let mut r = fixed();
        let ev = resolve_turn(&mut st, Act::Move(0), Act::Move(0), &mut r);
        assert!(ev.iter().any(|e| e["t"] == "faint" && e["side"] == 1));
        assert_eq!(needs_replace(&st), vec![1]);
        assert!(!st.over);
        let sw = replace(&mut st, 1, 1);
        assert_eq!(sw, vec![json!({"t": "switch", "side": 1, "slot": 1, "name": "Magikarp"})]);
        assert!(needs_replace(&st).is_empty());
        let mut r = fixed();
        let ev = resolve_turn(&mut st, Act::Move(0), Act::Move(0), &mut r);
        assert!(st.over);
        assert_eq!(st.winner, Some(0));
        assert_eq!(ev.last().unwrap(), &json!({"t": "end", "winner": 0}));
        // A finished battle asks nobody to replace.
        assert!(needs_replace(&st).is_empty());
    }

    #[test]
    fn a_switch_clears_the_boosts_and_the_toxic_ramp_of_whoever_leaves() {
        let mut st = new_battle(vec![mon(CHARIZARD), mon(MAGIKARP)], vec![mon(VENUSAUR)]);
        st.sides[0].team[0].boosts[0] = 3;
        st.sides[0].team[0].status = Some("tox".into());
        st.sides[0].team[0].tox = 7;
        let _ = replace(&mut st, 0, 1);
        assert_eq!(st.sides[0].team[0].boosts, [0; 7]);
        assert_eq!(st.sides[0].team[0].tox, 0);
        assert_eq!(st.sides[0].team[0].status.as_deref(), Some("tox")); // the status stays
        assert_eq!(st.sides[0].active, 1);
    }

    #[test]
    fn the_end_of_turn_residuals_are_burn_poison_and_a_ramping_toxic() {
        // Driven through `end_of_turn` itself rather than a whole turn, so no
        // attack's damage is mixed into the hp the residual takes.
        let residual = |status: &str, tox: i64| {
            let mut st = new_battle(vec![mon(CHARIZARD)], vec![mon(VENUSAUR)]);
            st.sides[0].team[0].status = Some(status.into());
            st.sides[0].team[0].tox = tox;
            let before = st.sides[0].team[0].hp;
            let mut r = fixed();
            let ev = {
                let mut t = Turn { s: &mut st, rng: &mut r, ev: Vec::new(), moved: [true, true] };
                t.end_of_turn();
                t.ev
            };
            (before - st.sides[0].team[0].hp, ev, st.sides[0].team[0].tox)
        };
        let (lost, ev, _) = residual("brn", 0);
        assert_eq!(lost, 167 / 16);
        assert_eq!(ev[0], json!({"t": "residual", "side": 0, "name": "Charizard", "hp": 167 - 10,
                                 "max": 167, "why": "brn"}));
        assert_eq!(residual("psn", 0).0, 167 / 8);
        // Toxic ramps BEFORE it bites, so the first tick is 1/16 and the next 2/16.
        let (lost, ev, tox) = residual("tox", 0);
        assert_eq!((lost, tox), (167 / 16, 1));
        assert_eq!(ev[0]["why"], "tox");
        assert_eq!(residual("tox", 7).0, 167 * 8 / 16);
        assert_eq!(residual("tox", 15).0, 167 * 15 / 16); // the ramp caps at 15
        // A fainted creature takes no residual at all.
        let mut st = new_battle(vec![mon(CHARIZARD)], vec![mon(VENUSAUR)]);
        st.sides[0].team[0].status = Some("brn".into());
        st.sides[0].team[0].hp = 0;
        st.sides[1].team[0].flinch = true;
        let mut r = fixed();
        let ev = {
            let mut t = Turn { s: &mut st, rng: &mut r, ev: Vec::new(), moved: [true, true] };
            t.end_of_turn();
            t.ev
        };
        assert!(ev.is_empty());
        assert!(!st.sides[1].team[0].flinch); // ... but every flinch is cleared
    }

    #[test]
    fn a_sleeping_creature_cannot_move_until_it_wakes() {
        let mut st = new_battle(vec![mon(CHARIZARD)], vec![mon(VENUSAUR)]);
        st.sides[0].team[0].status = Some("slp".into());
        st.sides[0].team[0].slp = 1;
        let mut r = fixed();
        let ev = resolve_turn(&mut st, Act::Move(0), Act::Move(0), &mut r);
        let cant = ev.iter().find(|e| e["t"] == "cant").unwrap();
        assert_eq!((cant["side"].as_i64().unwrap(), cant["why"].as_str().unwrap()), (0, "slp"));
        assert_eq!(st.sides[0].team[0].slp, 0);
        assert_eq!(st.sides[0].team[0].moves[0].pp, 15); // no PP spent
        // Out of sleep turns, it wakes and then acts in the same turn.
        let mut r = fixed();
        let ev = resolve_turn(&mut st, Act::Move(0), Act::Move(0), &mut r);
        assert_eq!(ev[0], json!({"t": "cure", "side": 0, "name": "Charizard", "s": "slp"}));
        assert!(st.sides[0].team[0].status.is_none());
        assert!(ev.iter().any(|e| e["t"] == "move" && e["side"] == 0));
    }

    #[test]
    fn a_status_move_boosts_its_user_or_the_foe_and_says_how_far_it_got() {
        // Scary Face drops the FOE's speed; Dragon Dance boosts its USER.
        let mut st = new_battle(vec![mon(CHARIZARD)], vec![mon(VENUSAUR)]);
        let mut r = fixed();
        let ev = resolve_turn(&mut st, Act::Move(3), Act::Move(3), &mut r);
        let b = evs(&ev, "boost");
        assert_eq!(b[0]["side"], 1); // Charizard's Scary Face hits side 1
        assert_eq!(b[0]["stat"], "spe");
        assert_eq!(b[0]["n"], -2);
        assert_eq!(b[0]["want"], -2);
        assert_eq!(st.sides[1].team[0].boosts[boost_i("spe").unwrap()], -2);
        // The clamp shows up as a smaller `n` than `want`.
        st.sides[1].team[0].boosts[boost_i("spe").unwrap()] = -5;
        let mut r = fixed();
        let ev = resolve_turn(&mut st, Act::Move(3), Act::Move(3), &mut r);
        let b = evs(&ev, "boost");
        assert_eq!((b[0]["n"].as_i64().unwrap(), b[0]["want"].as_i64().unwrap()), (-1, -2));
        assert_eq!(st.sides[1].team[0].boosts[boost_i("spe").unwrap()], -6);
    }

    #[test]
    fn a_heal_at_full_hp_fails_and_a_hurt_one_heals_half_rounded_half_up() {
        // Slowbro learns Slack Off (1/2) -- the only self-heal in the catalog
        // with a clean half.
        let heal = move_of("slackoff");
        assert_eq!(heal.heal, Some([1, 2]));
        assert_eq!(half_up(167.0 * 1.0 / 2.0), 84); // 83.5 goes UP, not to even
    }

    #[test]
    fn view_mon_sends_fourteen_keys_in_pythons_order_and_no_stats() {
        let m = mon(MAGIKARP);
        let v = view_mon(&m);
        let keys: Vec<_> = v.as_object().unwrap().keys().map(String::as_str).collect();
        assert_eq!(keys,
                   vec!["name", "id", "dex", "sprite", "mega", "shiny", "sp", "st", "lvl", "types",
                        "hp", "max", "status", "boosts", "moves"]);
        // `sprite` and `mega` and `status` are present as null, never omitted.
        assert_eq!(v["sprite"], Value::Null);
        assert_eq!(v["mega"], Value::Null);
        assert_eq!(v["status"], Value::Null);
        assert_eq!(v["boosts"].as_object().unwrap().keys().map(String::as_str).collect::<Vec<_>>(),
                   vec!["atk", "def", "spa", "spd", "spe", "accuracy", "evasion"]);
        assert_eq!(v["moves"], json!([{"id": "tackle", "pp": 35, "max": 35}]));
        assert!(v.get("stats").is_none()); // the page derives nothing
        // A mega carries its sprite, which is how the page picks the artwork.
        let mega = build_mon(&Spec { sp: 1, st: 4, br: None, mg: Some("charizard-megax".into()),
                                     sh: true, name: String::new() });
        let v = view_mon(&mega);
        assert_eq!((v["sprite"].as_i64().unwrap(), v["mega"].as_str().unwrap(), v["shiny"] == true),
                   (10034, "charizard-megax", true));
    }

    #[test]
    fn a_double_knockout_ends_the_battle_with_no_winner() {
        let mut st = new_battle(vec![mon(MAGIKARP)], vec![mon(MAGIKARP)]);
        st.sides[0].team[0].hp = 0;
        st.sides[1].team[0].hp = 0;
        let mut ev = Vec::new();
        finish(&mut st, &mut ev);
        assert!(st.over);
        assert_eq!(st.winner, None);
        assert_eq!(ev, vec![json!({"t": "end", "winner": null})]);
    }

    /// The one place this port is checked against the Python NUMBER FOR NUMBER
    /// rather than property by property. `FixedRng` is a constant 0.5, so these
    /// turns are fully determined -- they are not a seeded oracle (divergence 2)
    /// and they do not depend on a generator this port cannot reproduce. Each
    /// list below is `json.dumps(pb.resolve_turn(..))` out of
    /// `backend/app/pokebattle.py` run with a `lambda: 0.5`.
    #[test]
    fn a_whole_turn_matches_the_python_event_for_event() {
        let mut r = fixed();
        let mut st = new_battle(vec![mon(CHARIZARD)], vec![mon(VENUSAUR)]);
        assert_eq!(Value::Array(resolve_turn(&mut st, Act::Move(0), Act::Move(0), &mut r)),
                   json!([
            {"t": "move", "side": 0, "name": "Charizard", "move": "flareblitz"},
            {"t": "dmg", "side": 1, "name": "Venusaur", "hp": 6, "max": 170, "eff": 2.0,
             "crit": false, "move": "flareblitz"},
            {"t": "residual", "side": 0, "name": "Charizard", "hp": 113, "max": 167,
             "why": "recoil"},
            {"t": "move", "side": 1, "name": "Venusaur", "move": "powerwhip"},
            {"t": "dmg", "side": 0, "name": "Charizard", "hp": 92, "max": 167, "eff": 0.25,
             "crit": false, "move": "powerwhip"}]));
        assert_eq!((st.turn, st.over), (2, false));

        // Quick Attack goes first on priority and does nothing to a Ghost; the
        // "end" event closes the turn out.
        let mut st = new_battle(vec![mon(GENGAR)], vec![mon(PIKACHU18)]);
        assert_eq!(Value::Array(resolve_turn(&mut st, Act::Move(0), Act::Move(1), &mut r)),
                   json!([
            {"t": "move", "side": 1, "name": "Pikachu", "move": "quickattack"},
            {"t": "immune", "side": 0, "name": "Gengar"},
            {"t": "move", "side": 0, "name": "Gengar", "move": "shadowball"},
            {"t": "dmg", "side": 1, "name": "Pikachu", "hp": 0, "max": 46, "eff": 1.0,
             "crit": false, "move": "shadowball"},
            {"t": "faint", "side": 1, "name": "Pikachu"},
            {"t": "end", "winner": 0}]));
        assert_eq!((st.turn, st.over, st.winner), (2, true, Some(0)));

        // A faint, then the replace, then the win -- the whole of
        // test_duel_replace_phase_then_win's battle half.
        let mut st = new_battle(vec![mon(CHARIZARD)], vec![mon(MAGIKARP), mon(MAGIKARP)]);
        assert_eq!(Value::Array(resolve_turn(&mut st, Act::Move(0), Act::Move(0), &mut r)),
                   json!([
            {"t": "move", "side": 0, "name": "Charizard", "move": "flareblitz"},
            {"t": "dmg", "side": 1, "name": "Magikarp", "hp": 0, "max": 23, "eff": 0.5,
             "crit": false, "move": "flareblitz"},
            {"t": "faint", "side": 1, "name": "Magikarp"},
            {"t": "residual", "side": 0, "name": "Charizard", "hp": 159, "max": 167,
             "why": "recoil"}]));
        assert_eq!(needs_replace(&st), vec![1]);
        assert_eq!(Value::Array(replace(&mut st, 1, 1)),
                   json!([{"t": "switch", "side": 1, "slot": 1, "name": "Magikarp"}]));
        assert_eq!(Value::Array(resolve_turn(&mut st, Act::Move(0), Act::Move(0), &mut r)),
                   json!([
            {"t": "move", "side": 0, "name": "Charizard", "move": "flareblitz"},
            {"t": "dmg", "side": 1, "name": "Magikarp", "hp": 0, "max": 23, "eff": 0.5,
             "crit": false, "move": "flareblitz"},
            {"t": "faint", "side": 1, "name": "Magikarp"},
            {"t": "residual", "side": 0, "name": "Charizard", "hp": 151, "max": 167,
             "why": "recoil"},
            {"t": "end", "winner": 0}]));
        assert_eq!((st.turn, st.over, st.winner), (3, true, Some(0)));

        // Struggle: typeless, so `eff` is 1 even against a Water type, and it
        // costs its user a quarter of its max hp.
        let mut st = new_battle(vec![mon(MAGIKARP)], vec![mon(MAGIKARP)]);
        for m in &mut st.sides[0].team[0].moves {
            m.pp = 0;
        }
        assert_eq!(Value::Array(resolve_turn(&mut st, Act::Struggle, Act::Move(0), &mut r)),
                   json!([
            {"t": "move", "side": 1, "name": "Magikarp", "move": "tackle"},
            {"t": "dmg", "side": 0, "name": "Magikarp", "hp": 20, "max": 23, "eff": 1.0,
             "crit": false, "move": "tackle"},
            {"t": "move", "side": 0, "name": "Magikarp", "move": "struggle"},
            {"t": "dmg", "side": 1, "name": "Magikarp", "hp": 20, "max": 23, "eff": 1.0,
             "crit": false, "move": "struggle"},
            {"t": "residual", "side": 0, "name": "Magikarp", "hp": 14, "max": 23,
             "why": "recoil"}]));
    }

    #[test]
    fn a_move_at_a_fainted_target_fails_rather_than_hitting_nothing() {
        let mut st = new_battle(vec![mon(CHARIZARD)], vec![mon(MAGIKARP), mon(MAGIKARP)]);
        st.sides[1].team[0].hp = 0;
        let mut r = fixed();
        // Side 1 is fainted, so side 0's move has no target; the Python keeps
        // going rather than refusing the turn.
        let ev = resolve_turn(&mut st, Act::Move(0), Act::Move(0), &mut r);
        let fail = ev.iter().find(|e| e["t"] == "fail").unwrap();
        assert_eq!(fail["why"], "notarget");
        assert_eq!(fail["side"], 0); // the USER's side, with the user's name
        assert_eq!(fail["name"], "Charizard");
    }
}
