"""
Pokemon-style battle engine for the Valley Creature Duel (server-authoritative).

Data: app/data/pokemon.json, generated by tools/build_pokedata.mjs from Pokemon Showdown
(MIT, see LICENSES/pokemon-showdown-MIT.txt) and byte-identical to games/pokedata.js.

This module is a line-for-line mirror of the engine in games/pokebattle.js (the solo
battles run that one in the browser). Both draw randomness only through rng() -> [0, 1)
in the same order, so the same random stream gives the same turn; tests/test_pokebattle_parity.py
checks that. Clients only ever send {species, stage, branch, mega, shiny, name} per
creature and a move/switch choice; every stat, move, PP and damage number is derived here.
Stdlib only.
"""
import json
import math
from pathlib import Path
from typing import Any, Callable

DATA: dict = json.loads((Path(__file__).parent / "data" / "pokemon.json").read_text(encoding="utf-8"))
MOVES: dict = DATA["moves"]
STATS = ("atk", "def", "spa", "spd", "spe")
BOOSTS = ("atk", "def", "spa", "spd", "spe", "accuracy", "evasion")
CRIT_CHANCE = {1: 1 / 24, 2: 1 / 8, 3: 1 / 2}
STATUS_IMMUNE = {"par": ("Electric",), "brn": ("Fire",), "psn": ("Poison", "Steel"),
                 "tox": ("Poison", "Steel"), "slp": ()}
Rng = Callable[[], float]


def _int(v: Any) -> bool:
    return isinstance(v, int) and not isinstance(v, bool)


def half_up(x: float) -> int:
    """JS Math.round for the non-negative numbers used here; Python's round() is banker's."""
    return math.floor(x + 0.5)


def evo_pos(stage: int, length: int) -> int:
    return max(0, min(length - 1, half_up(stage / 4 * (length - 1))))


def eff(atk: str, dfn: str) -> float:
    return DATA["chart"].get(atk, {}).get(dfn, 1)


def type_mult(move_type: str, types: list) -> float:
    m = 1.0
    for t in types:
        m *= eff(move_type, t)
    return m


def calc_stat(base: int, level: int, hp: bool = False) -> int:
    core = (2 * base + 31) * level // 100
    return core + level + 10 if hp else core + 5


# ------------------------------------------------------------------ teams --
def clean_spec(raw: Any) -> dict | None:
    """One creature as a client may describe it; anything else is ignored."""
    if not isinstance(raw, dict):
        return None
    sp, st = raw.get("sp"), raw.get("st")
    if not _int(sp) or not 0 <= sp < len(DATA["lines"]) or not _int(st) or not 0 <= st <= 4:
        return None
    br, mg, name = raw.get("br"), raw.get("mg"), raw.get("name", raw.get("n"))
    name = "".join(ch for ch in name if ch.isprintable()).strip()[:24] if isinstance(name, str) else ""
    return {"sp": sp, "st": st, "br": br if _int(br) else None, "mg": mg if isinstance(mg, str) else None,
            "sh": raw.get("sh") is True or (_int(raw.get("sh")) and raw.get("sh") == 1), "name": name}


def build_mon(spec: dict) -> dict:
    """Everything about a battler, derived from (species, stage) + the vendored data."""
    sp, st = spec["sp"], spec["st"]
    line = DATA["lines"][sp]
    pos = evo_pos(st, len(line))
    dex = line[pos]
    mega = None
    if pos == len(line) - 1:
        opts = DATA["branches"].get(str(sp))
        if opts:
            dex = spec.get("br") if spec.get("br") in opts else opts[0]
        if st == 4 and spec.get("mg") in DATA["megaFor"].get(str(dex), []):
            mega = spec["mg"]
    pid = DATA["megas"][mega] if mega else DATA["byDex"][str(dex)]
    e = DATA["pokemon"][pid]
    lvl = DATA["levels"][st]
    stats = {"hp": calc_stat(e["bs"]["hp"], lvl, True)}
    for s in STATS:
        stats[s] = calc_stat(e["bs"][s], lvl)
    return {"name": e["name"], "id": pid, "dex": dex, "sprite": e.get("sprite"), "mega": mega,
            "shiny": bool(spec.get("sh")), "sp": sp, "st": st, "lvl": lvl, "types": list(e["types"]),
            "stats": stats, "hp": stats["hp"], "max": stats["hp"], "status": None, "slp": 0, "tox": 0,
            "flinch": False, "boosts": {b: 0 for b in BOOSTS},
            "moves": [{"id": m, "pp": MOVES[m]["pp"], "max": MOVES[m]["pp"]} for m in e["moves"][str(lvl)]]}


def new_battle(team_a: list, team_b: list) -> dict:
    return {"sides": [{"team": team_a, "active": 0}, {"team": team_b, "active": 0}], "turn": 1,
            "over": False, "winner": None}


def active(state: dict, side: int) -> dict:
    s = state["sides"][side]
    return s["team"][s["active"]]


def alive(state: dict, side: int) -> list[int]:
    return [i for i, m in enumerate(state["sides"][side]["team"]) if m["hp"] > 0]


def needs_replace(state: dict) -> list[int]:
    if state["over"]:
        return []
    return [i for i in (0, 1) if active(state, i)["hp"] <= 0 and alive(state, i)]


# ---------------------------------------------------------------- actions --
def legal(state: dict, side: int, act: Any) -> dict | None:
    """A normalised action, or None. A side that is out of PP always Struggles."""
    if state["over"] or not isinstance(act, dict):
        return None
    side_s = state["sides"][side]
    mon = side_s["team"][side_s["active"]]
    k = act.get("k")
    if k == "switch":
        to = act.get("to")
        if _int(to) and 0 <= to < len(side_s["team"]) and to != side_s["active"] and side_s["team"][to]["hp"] > 0:
            return {"k": "switch", "to": to}
        return None
    if mon["hp"] <= 0:
        return None
    if all(m["pp"] <= 0 for m in mon["moves"]):
        return {"k": "struggle"} if k in ("move", "struggle") else None
    i = act.get("i")
    if k == "move" and _int(i) and 0 <= i < len(mon["moves"]) and mon["moves"][i]["pp"] > 0:
        return {"k": "move", "i": i}
    return None


def auto_act(state: dict, side: int) -> dict:
    mon = active(state, side)
    for i, m in enumerate(mon["moves"]):
        if m["pp"] > 0:
            return {"k": "move", "i": i}
    return {"k": "struggle"}


def stage_mult_stat(stat: int, s: int) -> int:
    return stat * max(2, 2 + s) // max(2, 2 - s)


def speed(mon: dict) -> int:
    v = stage_mult_stat(mon["stats"]["spe"], mon["boosts"]["spe"])
    return v // 2 if mon["status"] == "par" else v


def damage(att: dict, dfn: dict, move: dict, crit: bool, roll: int) -> tuple[int, float]:
    """(damage, type multiplier) with the main-series formula; roll is 85..100."""
    mult = 1.0 if move["type"] == "???" else type_mult(move["type"], dfn["types"])
    if mult == 0:
        return 0, 0
    if move.get("fixed") == "level":
        return att["lvl"], mult
    phys = move["cat"] == "physical"
    a_key, d_key = ("atk", "def") if phys else ("spa", "spd")
    a_b, d_b = att["boosts"][a_key], dfn["boosts"][d_key]
    if crit:
        a_b, d_b = max(0, a_b), min(0, d_b)
    a = stage_mult_stat(att["stats"][a_key], a_b)
    d = stage_mult_stat(dfn["stats"][d_key], d_b)
    base = ((2 * att["lvl"] // 5 + 2) * move["bp"] * a // d) // 50 + 2
    if crit:
        base = math.floor(base * 1.5)
    base = base * roll // 100
    if move["type"] in att["types"]:
        base = math.floor(base * 1.5)
    base = math.floor(base * mult)
    if phys and att["status"] == "brn":
        base = math.floor(base * 0.5)
    return max(1, base), mult


# ------------------------------------------------------------------ turns --
class _Turn:
    def __init__(self, state: dict, rng: Rng):
        self.s, self.rng, self.ev = state, rng, []
        self.moved = [False, False]

    def mon(self, side: int) -> dict:
        return active(self.s, side)

    def switch(self, side: int, to: int) -> None:
        old = self.mon(side)
        old["boosts"] = {b: 0 for b in BOOSTS}
        old["flinch"] = False
        if old["status"] == "tox":
            old["tox"] = 0
        self.s["sides"][side]["active"] = to
        self.ev.append({"t": "switch", "side": side, "slot": to, "name": self.mon(side)["name"]})

    def boosts(self, side: int, boosts: dict) -> None:
        mon = self.mon(side)
        for stat in BOOSTS:
            if stat not in boosts:
                continue
            want = boosts[stat]
            cur = mon["boosts"][stat]
            new = max(-6, min(6, cur + want))
            mon["boosts"][stat] = new
            self.ev.append({"t": "boost", "side": side, "name": mon["name"], "stat": stat, "n": new - cur,
                            "want": want})

    def set_status(self, side: int, status: str, primary: bool) -> None:
        mon = self.mon(side)
        if mon["status"] or any(t in mon["types"] for t in STATUS_IMMUNE[status]):
            if primary:
                self.ev.append({"t": "fail", "side": side, "name": mon["name"],
                                "why": "already" if mon["status"] else "immune", "s": mon["status"]})
            return
        mon["status"] = status
        if status == "slp":
            mon["slp"] = 1 + math.floor(self.rng() * 3)
        if status == "tox":
            mon["tox"] = 0
        self.ev.append({"t": "status", "side": side, "name": mon["name"], "s": status})

    def heal(self, side: int, amount: int, why: str) -> None:
        mon = self.mon(side)
        mon["hp"] = min(mon["max"], mon["hp"] + amount)
        self.ev.append({"t": "heal", "side": side, "name": mon["name"], "hp": mon["hp"], "max": mon["max"], "why": why})

    def hurt(self, side: int, amount: int, why: str) -> None:
        mon = self.mon(side)
        mon["hp"] = max(0, mon["hp"] - amount)
        self.ev.append({"t": "residual", "side": side, "name": mon["name"], "hp": mon["hp"], "max": mon["max"], "why": why})
        if mon["hp"] <= 0:
            self.ev.append({"t": "faint", "side": side, "name": mon["name"]})

    def use_move(self, side: int, act: dict) -> None:
        user, foe = self.mon(side), 1 - side
        if user["hp"] <= 0:
            return
        if user["status"] == "slp":
            if user["slp"] > 0:
                user["slp"] -= 1
                self.ev.append({"t": "cant", "side": side, "name": user["name"], "why": "slp"})
                return
            user["status"] = None
            self.ev.append({"t": "cure", "side": side, "name": user["name"], "s": "slp"})
        if user["flinch"]:
            self.ev.append({"t": "cant", "side": side, "name": user["name"], "why": "flinch"})
            return
        if user["status"] == "par" and self.rng() < 0.25:
            self.ev.append({"t": "cant", "side": side, "name": user["name"], "why": "par"})
            return
        if act["k"] == "struggle":
            mid = "struggle"
        else:
            slot = user["moves"][act["i"]]
            slot["pp"] -= 1
            mid = slot["id"]
        mv = MOVES[mid]
        self.ev.append({"t": "move", "side": side, "name": user["name"], "move": mid})
        target_self = mv.get("self") == 1
        tgt = self.mon(foe)
        if not target_self and tgt["hp"] <= 0:
            self.ev.append({"t": "fail", "side": side, "name": user["name"], "why": "notarget"})
            return
        if not target_self and mv["acc"] > 0:
            s = max(-6, min(6, user["boosts"]["accuracy"] - tgt["boosts"]["evasion"]))
            num, den = (3 + s, 3) if s >= 0 else (3, 3 - s)
            if not self.rng() * 100 < mv["acc"] * num / den:
                self.ev.append({"t": "miss", "side": foe, "name": user["name"]})
                return
        if mv["cat"] == "status":
            if mv.get("heal"):
                if user["hp"] >= user["max"]:
                    self.ev.append({"t": "fail", "side": side, "name": user["name"], "why": "fullhp"})
                else:
                    self.heal(side, half_up(user["max"] * mv["heal"][0] / mv["heal"][1]), "move")
            elif mv.get("boosts"):
                self.boosts(side if target_self else foe, mv["boosts"])
            elif mv.get("status"):
                self.set_status(foe, mv["status"], True)
            return
        crit_stage = mv.get("crit", 1)
        crit = mv.get("fixed") != "level" and (crit_stage >= 4 or self.rng() < CRIT_CHANCE[crit_stage])
        roll = 85 + math.floor(self.rng() * 16) if mv.get("fixed") != "level" else 100
        dmg, mult = damage(user, tgt, mv, crit, roll)
        if mult == 0:
            self.ev.append({"t": "immune", "side": foe, "name": tgt["name"]})
            return
        dealt = min(dmg, tgt["hp"])
        tgt["hp"] -= dealt
        self.ev.append({"t": "dmg", "side": foe, "name": tgt["name"], "hp": tgt["hp"], "max": tgt["max"],
                        "eff": mult, "crit": crit, "move": mid})
        if tgt["hp"] <= 0:
            self.ev.append({"t": "faint", "side": foe, "name": tgt["name"]})
        if mv.get("drain") and user["hp"] < user["max"]:
            self.heal(side, max(1, half_up(dealt * mv["drain"][0] / mv["drain"][1])), "drain")
        sec = mv.get("sec")
        if sec and self.rng() * 100 < sec["chance"]:
            if tgt["hp"] > 0:
                if sec.get("status"):
                    self.set_status(foe, sec["status"], False)
                if sec.get("boosts"):
                    self.boosts(foe, sec["boosts"])
                if sec.get("volatileStatus") == "flinch" and not self.moved[foe]:
                    tgt["flinch"] = True
            if sec.get("self"):
                self.boosts(side, sec["self"]["boosts"])
        if mv.get("struggle"):
            self.hurt(side, max(1, half_up(user["max"] / 4)), "recoil")
        elif mv.get("recoil"):
            self.hurt(side, max(1, half_up(dealt * mv["recoil"][0] / mv["recoil"][1])), "recoil")

    def order(self, acts: list) -> list[int]:
        def key(side: int) -> tuple:
            a = acts[side]
            if a["k"] == "switch":
                return (1, 0, speed(self.mon(side)))
            mid = "struggle" if a["k"] == "struggle" else self.mon(side)["moves"][a["i"]]["id"]
            return (0, MOVES[mid]["pri"], speed(self.mon(side)))
        k0, k1 = key(0), key(1)
        if k0 == k1:
            return [0, 1] if self.rng() < 0.5 else [1, 0]
        return [0, 1] if k0 > k1 else [1, 0]

    def end_of_turn(self) -> None:
        for side in (0, 1):
            mon = self.mon(side)
            if mon["hp"] <= 0:
                continue
            if mon["status"] == "brn":
                self.hurt(side, max(1, mon["max"] // 16), "brn")
            elif mon["status"] == "psn":
                self.hurt(side, max(1, mon["max"] // 8), "psn")
            elif mon["status"] == "tox":
                mon["tox"] = min(15, mon["tox"] + 1)
                self.hurt(side, max(1, mon["max"] * mon["tox"] // 16), "tox")
        for side in (0, 1):
            self.mon(side)["flinch"] = False


def _finish(state: dict, ev: list) -> None:
    a, b = bool(alive(state, 0)), bool(alive(state, 1))
    if not (a and b):
        state["over"] = True
        state["winner"] = 0 if a else 1 if b else None
        ev.append({"t": "end", "winner": state["winner"]})


def resolve_turn(state: dict, act_a: dict, act_b: dict, rng: Rng) -> list[dict]:
    """Both sides' (already legal) actions -> ordered events; mutates state."""
    t = _Turn(state, rng)
    acts = [act_a, act_b]
    for side in t.order(acts):
        a = acts[side]
        if a["k"] == "switch":
            t.switch(side, a["to"])
        else:
            t.use_move(side, a)
        t.moved[side] = True
    t.end_of_turn()
    state["turn"] += 1
    _finish(state, t.ev)
    return t.ev


def replace(state: dict, side: int, slot: int) -> list[dict]:
    """A side whose active fainted sends in `slot` (must be alive)."""
    t = _Turn(state, lambda: 0.0)
    t.switch(side, slot)
    return t.ev


def view_mon(m: dict) -> dict:
    return {k: m[k] for k in ("name", "id", "dex", "sprite", "mega", "shiny", "sp", "st", "lvl", "types",
                              "hp", "max", "status", "boosts")} | {
        "moves": [dict(x) for x in m["moves"]]}
